/*
 * This file is generated by jOOQ.
 */
package com.example.jooq.tables;


import com.example.jooq.Keys;
import com.example.jooq.Public;
import com.example.jooq.tables.Agent.AgentPath;
import com.example.jooq.tables.Client.ClientPath;
import com.example.jooq.tables.records.AgentClientRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * Agent和Client的关联表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AgentClient extends TableImpl<AgentClientRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.agent_client</code>
     */
    public static final AgentClient AGENT_CLIENT = new AgentClient();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AgentClientRecord> getRecordType() {
        return AgentClientRecord.class;
    }

    /**
     * The column <code>public.agent_client.agent_id</code>. Agent ID
     */
    public final TableField<AgentClientRecord, Long> AGENT_ID = createField(DSL.name("agent_id"), SQLDataType.BIGINT.nullable(false), this, "Agent ID");

    /**
     * The column <code>public.agent_client.client_id</code>. Client ID
     */
    public final TableField<AgentClientRecord, Long> CLIENT_ID = createField(DSL.name("client_id"), SQLDataType.BIGINT.nullable(false), this, "Client ID");

    private AgentClient(Name alias, Table<AgentClientRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private AgentClient(Name alias, Table<AgentClientRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("Agent和Client的关联表"), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.agent_client</code> table reference
     */
    public AgentClient(String alias) {
        this(DSL.name(alias), AGENT_CLIENT);
    }

    /**
     * Create an aliased <code>public.agent_client</code> table reference
     */
    public AgentClient(Name alias) {
        this(alias, AGENT_CLIENT);
    }

    /**
     * Create a <code>public.agent_client</code> table reference
     */
    public AgentClient() {
        this(DSL.name("agent_client"), null);
    }

    public <O extends Record> AgentClient(Table<O> path, ForeignKey<O, AgentClientRecord> childPath, InverseForeignKey<O, AgentClientRecord> parentPath) {
        super(path, childPath, parentPath, AGENT_CLIENT);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class AgentClientPath extends AgentClient implements Path<AgentClientRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> AgentClientPath(Table<O> path, ForeignKey<O, AgentClientRecord> childPath, InverseForeignKey<O, AgentClientRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private AgentClientPath(Name alias, Table<AgentClientRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public AgentClientPath as(String alias) {
            return new AgentClientPath(DSL.name(alias), this);
        }

        @Override
        public AgentClientPath as(Name alias) {
            return new AgentClientPath(alias, this);
        }

        @Override
        public AgentClientPath as(Table<?> alias) {
            return new AgentClientPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<AgentClientRecord> getPrimaryKey() {
        return Keys.UK_AGENT_CLIENT_UNIQUE;
    }

    @Override
    public List<ForeignKey<AgentClientRecord, ?>> getReferences() {
        return Arrays.asList(Keys.AGENT_CLIENT__FK_AGENT_CLIENT_AGENT, Keys.AGENT_CLIENT__FK_AGENT_CLIENT_CLIENT);
    }

    private transient AgentPath _agent;

    /**
     * Get the implicit join path to the <code>public.agent</code> table.
     */
    public AgentPath agent() {
        if (_agent == null)
            _agent = new AgentPath(this, Keys.AGENT_CLIENT__FK_AGENT_CLIENT_AGENT, null);

        return _agent;
    }

    private transient ClientPath _client;

    /**
     * Get the implicit join path to the <code>public.client</code> table.
     */
    public ClientPath client() {
        if (_client == null)
            _client = new ClientPath(this, Keys.AGENT_CLIENT__FK_AGENT_CLIENT_CLIENT, null);

        return _client;
    }

    @Override
    public AgentClient as(String alias) {
        return new AgentClient(DSL.name(alias), this);
    }

    @Override
    public AgentClient as(Name alias) {
        return new AgentClient(alias, this);
    }

    @Override
    public AgentClient as(Table<?> alias) {
        return new AgentClient(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public AgentClient rename(String name) {
        return new AgentClient(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AgentClient rename(Name name) {
        return new AgentClient(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public AgentClient rename(Table<?> name) {
        return new AgentClient(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AgentClient where(Condition condition) {
        return new AgentClient(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AgentClient where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AgentClient where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AgentClient where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AgentClient where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AgentClient where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AgentClient where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AgentClient where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AgentClient whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AgentClient whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
