/*
 * This file is generated by jOOQ.
 */
package com.example.jooq.tables;


import com.example.jooq.Indexes;
import com.example.jooq.Keys;
import com.example.jooq.Public;
import com.example.jooq.tables.Agent.AgentPath;
import com.example.jooq.tables.Rag.RagPath;
import com.example.jooq.tables.records.AgentRagRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * Agent与RAG的关联表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AgentRag extends TableImpl<AgentRagRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.agent_rag</code>
     */
    public static final AgentRag AGENT_RAG = new AgentRag();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AgentRagRecord> getRecordType() {
        return AgentRagRecord.class;
    }

    /**
     * The column <code>public.agent_rag.agent_id</code>.
     */
    public final TableField<AgentRagRecord, Long> AGENT_ID = createField(DSL.name("agent_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.agent_rag.rag_id</code>.
     */
    public final TableField<AgentRagRecord, Long> RAG_ID = createField(DSL.name("rag_id"), SQLDataType.BIGINT.nullable(false), this, "");

    private AgentRag(Name alias, Table<AgentRagRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private AgentRag(Name alias, Table<AgentRagRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("Agent与RAG的关联表"), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.agent_rag</code> table reference
     */
    public AgentRag(String alias) {
        this(DSL.name(alias), AGENT_RAG);
    }

    /**
     * Create an aliased <code>public.agent_rag</code> table reference
     */
    public AgentRag(Name alias) {
        this(alias, AGENT_RAG);
    }

    /**
     * Create a <code>public.agent_rag</code> table reference
     */
    public AgentRag() {
        this(DSL.name("agent_rag"), null);
    }

    public <O extends Record> AgentRag(Table<O> path, ForeignKey<O, AgentRagRecord> childPath, InverseForeignKey<O, AgentRagRecord> parentPath) {
        super(path, childPath, parentPath, AGENT_RAG);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class AgentRagPath extends AgentRag implements Path<AgentRagRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> AgentRagPath(Table<O> path, ForeignKey<O, AgentRagRecord> childPath, InverseForeignKey<O, AgentRagRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private AgentRagPath(Name alias, Table<AgentRagRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public AgentRagPath as(String alias) {
            return new AgentRagPath(DSL.name(alias), this);
        }

        @Override
        public AgentRagPath as(Name alias) {
            return new AgentRagPath(alias, this);
        }

        @Override
        public AgentRagPath as(Table<?> alias) {
            return new AgentRagPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_AGENT_RAG_AGENT_ID, Indexes.IDX_AGENT_RAG_RAG_ID);
    }

    @Override
    public UniqueKey<AgentRagRecord> getPrimaryKey() {
        return Keys.PK_AGENT_RAG;
    }

    @Override
    public List<ForeignKey<AgentRagRecord, ?>> getReferences() {
        return Arrays.asList(Keys.AGENT_RAG__FK_AGENT_RAG_AGENT, Keys.AGENT_RAG__FK_AGENT_RAG_RAG);
    }

    private transient AgentPath _agent;

    /**
     * Get the implicit join path to the <code>public.agent</code> table.
     */
    public AgentPath agent() {
        if (_agent == null)
            _agent = new AgentPath(this, Keys.AGENT_RAG__FK_AGENT_RAG_AGENT, null);

        return _agent;
    }

    private transient RagPath _rag;

    /**
     * Get the implicit join path to the <code>public.rag</code> table.
     */
    public RagPath rag() {
        if (_rag == null)
            _rag = new RagPath(this, Keys.AGENT_RAG__FK_AGENT_RAG_RAG, null);

        return _rag;
    }

    @Override
    public AgentRag as(String alias) {
        return new AgentRag(DSL.name(alias), this);
    }

    @Override
    public AgentRag as(Name alias) {
        return new AgentRag(alias, this);
    }

    @Override
    public AgentRag as(Table<?> alias) {
        return new AgentRag(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public AgentRag rename(String name) {
        return new AgentRag(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AgentRag rename(Name name) {
        return new AgentRag(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public AgentRag rename(Table<?> name) {
        return new AgentRag(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AgentRag where(Condition condition) {
        return new AgentRag(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AgentRag where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AgentRag where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AgentRag where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AgentRag where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AgentRag where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AgentRag where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AgentRag where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AgentRag whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AgentRag whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
