/*
 * This file is generated by jOOQ.
 */
package com.example.jooq.tables;


import com.example.jooq.Indexes;
import com.example.jooq.Keys;
import com.example.jooq.Public;
import com.example.jooq.tables.AgentMemory.AgentMemoryPath;
import com.example.jooq.tables.AgentModel.AgentModelPath;
import com.example.jooq.tables.AgentRag.AgentRagPath;
import com.example.jooq.tables.Model.ModelPath;
import com.example.jooq.tables.Orchestrator.OrchestratorPath;
import com.example.jooq.tables.OrchestratorAgent.OrchestratorAgentPath;
import com.example.jooq.tables.Rag.RagPath;
import com.example.jooq.tables.records.AgentRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * Agent表（智能体）
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Agent extends TableImpl<AgentRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.agent</code>
     */
    public static final Agent AGENT = new Agent();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AgentRecord> getRecordType() {
        return AgentRecord.class;
    }

    /**
     * The column <code>public.agent.id</code>.
     */
    public final TableField<AgentRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.agent.name</code>.
     */
    public final TableField<AgentRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.agent.description</code>.
     */
    public final TableField<AgentRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.agent.status</code>.
     */
    public final TableField<AgentRecord, String> STATUS = createField(DSL.name("status"), SQLDataType.VARCHAR(50).defaultValue(DSL.field(DSL.raw("'ACTIVE'::character varying"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>public.agent.created_at</code>.
     */
    public final TableField<AgentRecord, Long> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.BIGINT.defaultValue(DSL.field(DSL.raw("(EXTRACT(epoch FROM CURRENT_TIMESTAMP))::bigint"), SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>public.agent.updated_at</code>.
     */
    public final TableField<AgentRecord, Long> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.BIGINT.defaultValue(DSL.field(DSL.raw("(EXTRACT(epoch FROM CURRENT_TIMESTAMP))::bigint"), SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>public.agent.system_prompt</code>. 系统提示词（System Prompt）
     */
    public final TableField<AgentRecord, String> SYSTEM_PROMPT = createField(DSL.name("system_prompt"), SQLDataType.CLOB, this, "系统提示词（System Prompt）");

    private Agent(Name alias, Table<AgentRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Agent(Name alias, Table<AgentRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("Agent表（智能体）"), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.agent</code> table reference
     */
    public Agent(String alias) {
        this(DSL.name(alias), AGENT);
    }

    /**
     * Create an aliased <code>public.agent</code> table reference
     */
    public Agent(Name alias) {
        this(alias, AGENT);
    }

    /**
     * Create a <code>public.agent</code> table reference
     */
    public Agent() {
        this(DSL.name("agent"), null);
    }

    public <O extends Record> Agent(Table<O> path, ForeignKey<O, AgentRecord> childPath, InverseForeignKey<O, AgentRecord> parentPath) {
        super(path, childPath, parentPath, AGENT);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class AgentPath extends Agent implements Path<AgentRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> AgentPath(Table<O> path, ForeignKey<O, AgentRecord> childPath, InverseForeignKey<O, AgentRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private AgentPath(Name alias, Table<AgentRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public AgentPath as(String alias) {
            return new AgentPath(DSL.name(alias), this);
        }

        @Override
        public AgentPath as(Name alias) {
            return new AgentPath(alias, this);
        }

        @Override
        public AgentPath as(Table<?> alias) {
            return new AgentPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_AGENT_STATUS);
    }

    @Override
    public Identity<AgentRecord, Long> getIdentity() {
        return (Identity<AgentRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<AgentRecord> getPrimaryKey() {
        return Keys.AGENT_PKEY;
    }

    private transient AgentMemoryPath _agentMemory;

    /**
     * Get the implicit to-many join path to the
     * <code>public.agent_memory</code> table
     */
    public AgentMemoryPath agentMemory() {
        if (_agentMemory == null)
            _agentMemory = new AgentMemoryPath(this, null, Keys.AGENT_MEMORY__FK_AGENT_MEMORY_AGENT.getInverseKey());

        return _agentMemory;
    }

    private transient AgentModelPath _agentModel;

    /**
     * Get the implicit to-many join path to the <code>public.agent_model</code>
     * table
     */
    public AgentModelPath agentModel() {
        if (_agentModel == null)
            _agentModel = new AgentModelPath(this, null, Keys.AGENT_MODEL__FK_AGENT_MODEL_AGENT.getInverseKey());

        return _agentModel;
    }

    private transient AgentRagPath _agentRag;

    /**
     * Get the implicit to-many join path to the <code>public.agent_rag</code>
     * table
     */
    public AgentRagPath agentRag() {
        if (_agentRag == null)
            _agentRag = new AgentRagPath(this, null, Keys.AGENT_RAG__FK_AGENT_RAG_AGENT.getInverseKey());

        return _agentRag;
    }

    private transient OrchestratorAgentPath _orchestratorAgent;

    /**
     * Get the implicit to-many join path to the
     * <code>public.orchestrator_agent</code> table
     */
    public OrchestratorAgentPath orchestratorAgent() {
        if (_orchestratorAgent == null)
            _orchestratorAgent = new OrchestratorAgentPath(this, null, Keys.ORCHESTRATOR_AGENT__FK_ORCHESTRATOR_AGENT_AGENT.getInverseKey());

        return _orchestratorAgent;
    }

    /**
     * Get the implicit many-to-many join path to the <code>public.model</code>
     * table
     */
    public ModelPath model() {
        return agentModel().model();
    }

    /**
     * Get the implicit many-to-many join path to the <code>public.rag</code>
     * table
     */
    public RagPath rag() {
        return agentRag().rag();
    }

    /**
     * Get the implicit many-to-many join path to the
     * <code>public.orchestrator</code> table
     */
    public OrchestratorPath orchestrator() {
        return orchestratorAgent().orchestrator();
    }

    @Override
    public Agent as(String alias) {
        return new Agent(DSL.name(alias), this);
    }

    @Override
    public Agent as(Name alias) {
        return new Agent(alias, this);
    }

    @Override
    public Agent as(Table<?> alias) {
        return new Agent(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Agent rename(String name) {
        return new Agent(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Agent rename(Name name) {
        return new Agent(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Agent rename(Table<?> name) {
        return new Agent(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Agent where(Condition condition) {
        return new Agent(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Agent where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Agent where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Agent where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Agent where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Agent where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Agent where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Agent where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Agent whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Agent whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
