/*
 * This file is generated by jOOQ.
 */
package com.example.jooq.tables;


import com.example.jooq.Keys;
import com.example.jooq.Public;
import com.example.jooq.tables.records.AgentMcpRecord;

import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AgentMcp extends TableImpl<AgentMcpRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.agent_mcp</code>
     */
    public static final AgentMcp AGENT_MCP = new AgentMcp();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AgentMcpRecord> getRecordType() {
        return AgentMcpRecord.class;
    }

    /**
     * The column <code>public.agent_mcp.agent_id</code>.
     */
    public final TableField<AgentMcpRecord, Long> AGENT_ID = createField(DSL.name("agent_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.agent_mcp.mcp_id</code>.
     */
    public final TableField<AgentMcpRecord, Long> MCP_ID = createField(DSL.name("mcp_id"), SQLDataType.BIGINT.nullable(false), this, "");

    private AgentMcp(Name alias, Table<AgentMcpRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private AgentMcp(Name alias, Table<AgentMcpRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.agent_mcp</code> table reference
     */
    public AgentMcp(String alias) {
        this(DSL.name(alias), AGENT_MCP);
    }

    /**
     * Create an aliased <code>public.agent_mcp</code> table reference
     */
    public AgentMcp(Name alias) {
        this(alias, AGENT_MCP);
    }

    /**
     * Create a <code>public.agent_mcp</code> table reference
     */
    public AgentMcp() {
        this(DSL.name("agent_mcp"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<AgentMcpRecord> getPrimaryKey() {
        return Keys.PK_AGENT_MCP;
    }

    @Override
    public AgentMcp as(String alias) {
        return new AgentMcp(DSL.name(alias), this);
    }

    @Override
    public AgentMcp as(Name alias) {
        return new AgentMcp(alias, this);
    }

    @Override
    public AgentMcp as(Table<?> alias) {
        return new AgentMcp(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public AgentMcp rename(String name) {
        return new AgentMcp(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AgentMcp rename(Name name) {
        return new AgentMcp(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public AgentMcp rename(Table<?> name) {
        return new AgentMcp(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AgentMcp where(Condition condition) {
        return new AgentMcp(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AgentMcp where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AgentMcp where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AgentMcp where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AgentMcp where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AgentMcp where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AgentMcp where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AgentMcp where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AgentMcp whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AgentMcp whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
