/*
 * This file is generated by jOOQ.
 */
package com.example.jooq.tables;


import com.example.jooq.Indexes;
import com.example.jooq.Keys;
import com.example.jooq.Public;
import com.example.jooq.tables.Agent.AgentPath;
import com.example.jooq.tables.records.AgentMemoryRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.JSONB;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * Agent共享记忆表，支持会话级和全局级别的记忆存储
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AgentMemory extends TableImpl<AgentMemoryRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.agent_memory</code>
     */
    public static final AgentMemory AGENT_MEMORY = new AgentMemory();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AgentMemoryRecord> getRecordType() {
        return AgentMemoryRecord.class;
    }

    /**
     * The column <code>public.agent_memory.id</code>.
     */
    public final TableField<AgentMemoryRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.agent_memory.session_id</code>. 会话ID，为空表示全局记忆
     */
    public final TableField<AgentMemoryRecord, String> SESSION_ID = createField(DSL.name("session_id"), SQLDataType.VARCHAR(255), this, "会话ID，为空表示全局记忆");

    /**
     * The column <code>public.agent_memory.agent_id</code>. Agent
     * ID，为空表示所有Agent共享
     */
    public final TableField<AgentMemoryRecord, Long> AGENT_ID = createField(DSL.name("agent_id"), SQLDataType.BIGINT, this, "Agent ID，为空表示所有Agent共享");

    /**
     * The column <code>public.agent_memory.memory_key</code>. 记忆键
     */
    public final TableField<AgentMemoryRecord, String> MEMORY_KEY = createField(DSL.name("memory_key"), SQLDataType.VARCHAR(255).nullable(false), this, "记忆键");

    /**
     * The column <code>public.agent_memory.memory_value</code>. 记忆值
     */
    public final TableField<AgentMemoryRecord, String> MEMORY_VALUE = createField(DSL.name("memory_value"), SQLDataType.CLOB, this, "记忆值");

    /**
     * The column <code>public.agent_memory.memory_type</code>. 记忆类型
     */
    public final TableField<AgentMemoryRecord, String> MEMORY_TYPE = createField(DSL.name("memory_type"), SQLDataType.VARCHAR(50).defaultValue(DSL.field(DSL.raw("'KV'::character varying"), SQLDataType.VARCHAR)), this, "记忆类型");

    /**
     * The column <code>public.agent_memory.tags</code>. 标签数组
     */
    public final TableField<AgentMemoryRecord, String[]> TAGS = createField(DSL.name("tags"), SQLDataType.CLOB.array(), this, "标签数组");

    /**
     * The column <code>public.agent_memory.expires_at</code>. 过期时间戳
     */
    public final TableField<AgentMemoryRecord, Long> EXPIRES_AT = createField(DSL.name("expires_at"), SQLDataType.BIGINT, this, "过期时间戳");

    /**
     * The column <code>public.agent_memory.metadata</code>.
     */
    public final TableField<AgentMemoryRecord, JSONB> METADATA = createField(DSL.name("metadata"), SQLDataType.JSONB, this, "");

    /**
     * The column <code>public.agent_memory.created_at</code>.
     */
    public final TableField<AgentMemoryRecord, Long> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.BIGINT.defaultValue(DSL.field(DSL.raw("(EXTRACT(epoch FROM CURRENT_TIMESTAMP))::bigint"), SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>public.agent_memory.updated_at</code>.
     */
    public final TableField<AgentMemoryRecord, Long> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.BIGINT.defaultValue(DSL.field(DSL.raw("(EXTRACT(epoch FROM CURRENT_TIMESTAMP))::bigint"), SQLDataType.BIGINT)), this, "");

    private AgentMemory(Name alias, Table<AgentMemoryRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private AgentMemory(Name alias, Table<AgentMemoryRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("Agent共享记忆表，支持会话级和全局级别的记忆存储"), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.agent_memory</code> table reference
     */
    public AgentMemory(String alias) {
        this(DSL.name(alias), AGENT_MEMORY);
    }

    /**
     * Create an aliased <code>public.agent_memory</code> table reference
     */
    public AgentMemory(Name alias) {
        this(alias, AGENT_MEMORY);
    }

    /**
     * Create a <code>public.agent_memory</code> table reference
     */
    public AgentMemory() {
        this(DSL.name("agent_memory"), null);
    }

    public <O extends Record> AgentMemory(Table<O> path, ForeignKey<O, AgentMemoryRecord> childPath, InverseForeignKey<O, AgentMemoryRecord> parentPath) {
        super(path, childPath, parentPath, AGENT_MEMORY);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class AgentMemoryPath extends AgentMemory implements Path<AgentMemoryRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> AgentMemoryPath(Table<O> path, ForeignKey<O, AgentMemoryRecord> childPath, InverseForeignKey<O, AgentMemoryRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private AgentMemoryPath(Name alias, Table<AgentMemoryRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public AgentMemoryPath as(String alias) {
            return new AgentMemoryPath(DSL.name(alias), this);
        }

        @Override
        public AgentMemoryPath as(Name alias) {
            return new AgentMemoryPath(alias, this);
        }

        @Override
        public AgentMemoryPath as(Table<?> alias) {
            return new AgentMemoryPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_AGENT_MEMORY_AGENT_ID, Indexes.IDX_AGENT_MEMORY_EXPIRES_AT, Indexes.IDX_AGENT_MEMORY_KEY, Indexes.IDX_AGENT_MEMORY_SESSION_ID, Indexes.IDX_AGENT_MEMORY_TAGS, Indexes.IDX_AGENT_MEMORY_TYPE);
    }

    @Override
    public Identity<AgentMemoryRecord, Long> getIdentity() {
        return (Identity<AgentMemoryRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<AgentMemoryRecord> getPrimaryKey() {
        return Keys.AGENT_MEMORY_PKEY;
    }

    @Override
    public List<ForeignKey<AgentMemoryRecord, ?>> getReferences() {
        return Arrays.asList(Keys.AGENT_MEMORY__FK_AGENT_MEMORY_AGENT);
    }

    private transient AgentPath _agent;

    /**
     * Get the implicit join path to the <code>public.agent</code> table.
     */
    public AgentPath agent() {
        if (_agent == null)
            _agent = new AgentPath(this, Keys.AGENT_MEMORY__FK_AGENT_MEMORY_AGENT, null);

        return _agent;
    }

    @Override
    public AgentMemory as(String alias) {
        return new AgentMemory(DSL.name(alias), this);
    }

    @Override
    public AgentMemory as(Name alias) {
        return new AgentMemory(alias, this);
    }

    @Override
    public AgentMemory as(Table<?> alias) {
        return new AgentMemory(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public AgentMemory rename(String name) {
        return new AgentMemory(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AgentMemory rename(Name name) {
        return new AgentMemory(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public AgentMemory rename(Table<?> name) {
        return new AgentMemory(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AgentMemory where(Condition condition) {
        return new AgentMemory(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AgentMemory where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AgentMemory where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AgentMemory where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AgentMemory where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AgentMemory where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AgentMemory where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AgentMemory where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AgentMemory whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AgentMemory whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
