/*
 * This file is generated by jOOQ.
 */
package com.example.jooq.tables;


import com.example.jooq.Keys;
import com.example.jooq.Public;
import com.example.jooq.tables.records.AgentModelRecord;

import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AgentModel extends TableImpl<AgentModelRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.agent_model</code>
     */
    public static final AgentModel AGENT_MODEL = new AgentModel();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AgentModelRecord> getRecordType() {
        return AgentModelRecord.class;
    }

    /**
     * The column <code>public.agent_model.agent_id</code>.
     */
    public final TableField<AgentModelRecord, Long> AGENT_ID = createField(DSL.name("agent_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.agent_model.model_id</code>.
     */
    public final TableField<AgentModelRecord, Long> MODEL_ID = createField(DSL.name("model_id"), SQLDataType.BIGINT.nullable(false), this, "");

    private AgentModel(Name alias, Table<AgentModelRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private AgentModel(Name alias, Table<AgentModelRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.agent_model</code> table reference
     */
    public AgentModel(String alias) {
        this(DSL.name(alias), AGENT_MODEL);
    }

    /**
     * Create an aliased <code>public.agent_model</code> table reference
     */
    public AgentModel(Name alias) {
        this(alias, AGENT_MODEL);
    }

    /**
     * Create a <code>public.agent_model</code> table reference
     */
    public AgentModel() {
        this(DSL.name("agent_model"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<AgentModelRecord> getPrimaryKey() {
        return Keys.PK_AGENT_MODEL;
    }

    @Override
    public AgentModel as(String alias) {
        return new AgentModel(DSL.name(alias), this);
    }

    @Override
    public AgentModel as(Name alias) {
        return new AgentModel(alias, this);
    }

    @Override
    public AgentModel as(Table<?> alias) {
        return new AgentModel(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public AgentModel rename(String name) {
        return new AgentModel(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AgentModel rename(Name name) {
        return new AgentModel(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public AgentModel rename(Table<?> name) {
        return new AgentModel(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AgentModel where(Condition condition) {
        return new AgentModel(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AgentModel where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AgentModel where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AgentModel where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AgentModel where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AgentModel where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AgentModel where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AgentModel where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AgentModel whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AgentModel whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
