/*
 * This file is generated by jOOQ.
 */
package com.example.jooq.tables;


import com.example.jooq.Keys;
import com.example.jooq.Public;
import com.example.jooq.tables.AgentClient.AgentClientPath;
import com.example.jooq.tables.Client.ClientPath;
import com.example.jooq.tables.records.AgentRecord;

import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * Agent表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Agent extends TableImpl<AgentRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.agent</code>
     */
    public static final Agent AGENT = new Agent();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AgentRecord> getRecordType() {
        return AgentRecord.class;
    }

    /**
     * The column <code>public.agent.id</code>. 主键ID
     */
    public final TableField<AgentRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "主键ID");

    /**
     * The column <code>public.agent.name</code>. Agent名称
     */
    public final TableField<AgentRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(255).nullable(false), this, "Agent名称");

    /**
     * The column <code>public.agent.description</code>. Agent描述
     */
    public final TableField<AgentRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.CLOB, this, "Agent描述");

    /**
     * The column <code>public.agent.status</code>. 状态：ACTIVE, INACTIVE
     */
    public final TableField<AgentRecord, String> STATUS = createField(DSL.name("status"), SQLDataType.VARCHAR(50).defaultValue(DSL.field(DSL.raw("'ACTIVE'::character varying"), SQLDataType.VARCHAR)), this, "状态：ACTIVE, INACTIVE");

    /**
     * The column <code>public.agent.created_at</code>. 创建时间（时间戳，秒）
     */
    public final TableField<AgentRecord, Long> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.BIGINT.defaultValue(DSL.field(DSL.raw("(EXTRACT(epoch FROM CURRENT_TIMESTAMP))::bigint"), SQLDataType.BIGINT)), this, "创建时间（时间戳，秒）");

    /**
     * The column <code>public.agent.updated_at</code>. 更新时间（时间戳，秒）
     */
    public final TableField<AgentRecord, Long> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.BIGINT.defaultValue(DSL.field(DSL.raw("(EXTRACT(epoch FROM CURRENT_TIMESTAMP))::bigint"), SQLDataType.BIGINT)), this, "更新时间（时间戳，秒）");

    private Agent(Name alias, Table<AgentRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Agent(Name alias, Table<AgentRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("Agent表"), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.agent</code> table reference
     */
    public Agent(String alias) {
        this(DSL.name(alias), AGENT);
    }

    /**
     * Create an aliased <code>public.agent</code> table reference
     */
    public Agent(Name alias) {
        this(alias, AGENT);
    }

    /**
     * Create a <code>public.agent</code> table reference
     */
    public Agent() {
        this(DSL.name("agent"), null);
    }

    public <O extends Record> Agent(Table<O> path, ForeignKey<O, AgentRecord> childPath, InverseForeignKey<O, AgentRecord> parentPath) {
        super(path, childPath, parentPath, AGENT);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class AgentPath extends Agent implements Path<AgentRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> AgentPath(Table<O> path, ForeignKey<O, AgentRecord> childPath, InverseForeignKey<O, AgentRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private AgentPath(Name alias, Table<AgentRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public AgentPath as(String alias) {
            return new AgentPath(DSL.name(alias), this);
        }

        @Override
        public AgentPath as(Name alias) {
            return new AgentPath(alias, this);
        }

        @Override
        public AgentPath as(Table<?> alias) {
            return new AgentPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<AgentRecord, Long> getIdentity() {
        return (Identity<AgentRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<AgentRecord> getPrimaryKey() {
        return Keys.AGENT_PKEY;
    }

    private transient AgentClientPath _agentClient;

    /**
     * Get the implicit to-many join path to the
     * <code>public.agent_client</code> table
     */
    public AgentClientPath agentClient() {
        if (_agentClient == null)
            _agentClient = new AgentClientPath(this, null, Keys.AGENT_CLIENT__FK_AGENT_CLIENT_AGENT.getInverseKey());

        return _agentClient;
    }

    /**
     * Get the implicit many-to-many join path to the <code>public.client</code>
     * table
     */
    public ClientPath client() {
        return agentClient().client();
    }

    @Override
    public Agent as(String alias) {
        return new Agent(DSL.name(alias), this);
    }

    @Override
    public Agent as(Name alias) {
        return new Agent(alias, this);
    }

    @Override
    public Agent as(Table<?> alias) {
        return new Agent(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Agent rename(String name) {
        return new Agent(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Agent rename(Name name) {
        return new Agent(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Agent rename(Table<?> name) {
        return new Agent(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Agent where(Condition condition) {
        return new Agent(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Agent where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Agent where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Agent where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Agent where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Agent where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Agent where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Agent where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Agent whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Agent whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
