/*
 * This file is generated by jOOQ.
 */
package com.example.jooq.tables;


import com.example.jooq.Keys;
import com.example.jooq.Public;
import com.example.jooq.tables.Client.ClientPath;
import com.example.jooq.tables.Rag.RagPath;
import com.example.jooq.tables.records.ClientRagRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * Client和RAG的关联表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ClientRag extends TableImpl<ClientRagRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.client_rag</code>
     */
    public static final ClientRag CLIENT_RAG = new ClientRag();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ClientRagRecord> getRecordType() {
        return ClientRagRecord.class;
    }

    /**
     * The column <code>public.client_rag.client_id</code>. Client ID
     */
    public final TableField<ClientRagRecord, Long> CLIENT_ID = createField(DSL.name("client_id"), SQLDataType.BIGINT.nullable(false), this, "Client ID");

    /**
     * The column <code>public.client_rag.rag_id</code>. RAG ID
     */
    public final TableField<ClientRagRecord, Long> RAG_ID = createField(DSL.name("rag_id"), SQLDataType.BIGINT.nullable(false), this, "RAG ID");

    private ClientRag(Name alias, Table<ClientRagRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ClientRag(Name alias, Table<ClientRagRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("Client和RAG的关联表"), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.client_rag</code> table reference
     */
    public ClientRag(String alias) {
        this(DSL.name(alias), CLIENT_RAG);
    }

    /**
     * Create an aliased <code>public.client_rag</code> table reference
     */
    public ClientRag(Name alias) {
        this(alias, CLIENT_RAG);
    }

    /**
     * Create a <code>public.client_rag</code> table reference
     */
    public ClientRag() {
        this(DSL.name("client_rag"), null);
    }

    public <O extends Record> ClientRag(Table<O> path, ForeignKey<O, ClientRagRecord> childPath, InverseForeignKey<O, ClientRagRecord> parentPath) {
        super(path, childPath, parentPath, CLIENT_RAG);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ClientRagPath extends ClientRag implements Path<ClientRagRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ClientRagPath(Table<O> path, ForeignKey<O, ClientRagRecord> childPath, InverseForeignKey<O, ClientRagRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ClientRagPath(Name alias, Table<ClientRagRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ClientRagPath as(String alias) {
            return new ClientRagPath(DSL.name(alias), this);
        }

        @Override
        public ClientRagPath as(Name alias) {
            return new ClientRagPath(alias, this);
        }

        @Override
        public ClientRagPath as(Table<?> alias) {
            return new ClientRagPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<ClientRagRecord> getPrimaryKey() {
        return Keys.UK_CLIENT_RAG_UNIQUE;
    }

    @Override
    public List<ForeignKey<ClientRagRecord, ?>> getReferences() {
        return Arrays.asList(Keys.CLIENT_RAG__FK_CLIENT_RAG_CLIENT, Keys.CLIENT_RAG__FK_CLIENT_RAG_RAG);
    }

    private transient ClientPath _client;

    /**
     * Get the implicit join path to the <code>public.client</code> table.
     */
    public ClientPath client() {
        if (_client == null)
            _client = new ClientPath(this, Keys.CLIENT_RAG__FK_CLIENT_RAG_CLIENT, null);

        return _client;
    }

    private transient RagPath _rag;

    /**
     * Get the implicit join path to the <code>public.rag</code> table.
     */
    public RagPath rag() {
        if (_rag == null)
            _rag = new RagPath(this, Keys.CLIENT_RAG__FK_CLIENT_RAG_RAG, null);

        return _rag;
    }

    @Override
    public ClientRag as(String alias) {
        return new ClientRag(DSL.name(alias), this);
    }

    @Override
    public ClientRag as(Name alias) {
        return new ClientRag(alias, this);
    }

    @Override
    public ClientRag as(Table<?> alias) {
        return new ClientRag(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ClientRag rename(String name) {
        return new ClientRag(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ClientRag rename(Name name) {
        return new ClientRag(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ClientRag rename(Table<?> name) {
        return new ClientRag(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ClientRag where(Condition condition) {
        return new ClientRag(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ClientRag where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ClientRag where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ClientRag where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ClientRag where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ClientRag where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ClientRag where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ClientRag where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ClientRag whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ClientRag whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
