/*
 * This file is generated by jOOQ.
 */
package com.example.jooq.tables;


import com.example.jooq.Keys;
import com.example.jooq.Public;
import com.example.jooq.tables.Agent.AgentPath;
import com.example.jooq.tables.AgentClient.AgentClientPath;
import com.example.jooq.tables.ClientModel.ClientModelPath;
import com.example.jooq.tables.ClientRag.ClientRagPath;
import com.example.jooq.tables.Model.ModelPath;
import com.example.jooq.tables.Rag.RagPath;
import com.example.jooq.tables.records.ClientRecord;

import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * Client表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Client extends TableImpl<ClientRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.client</code>
     */
    public static final Client CLIENT = new Client();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ClientRecord> getRecordType() {
        return ClientRecord.class;
    }

    /**
     * The column <code>public.client.id</code>. 主键ID
     */
    public final TableField<ClientRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "主键ID");

    /**
     * The column <code>public.client.name</code>. Client名称
     */
    public final TableField<ClientRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(255).nullable(false), this, "Client名称");

    /**
     * The column <code>public.client.description</code>. Client描述
     */
    public final TableField<ClientRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.CLOB, this, "Client描述");

    /**
     * The column <code>public.client.status</code>. 状态：ACTIVE, INACTIVE
     */
    public final TableField<ClientRecord, String> STATUS = createField(DSL.name("status"), SQLDataType.VARCHAR(50).defaultValue(DSL.field(DSL.raw("'ACTIVE'::character varying"), SQLDataType.VARCHAR)), this, "状态：ACTIVE, INACTIVE");

    /**
     * The column <code>public.client.created_at</code>. 创建时间（时间戳，秒）
     */
    public final TableField<ClientRecord, Long> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.BIGINT.defaultValue(DSL.field(DSL.raw("(EXTRACT(epoch FROM CURRENT_TIMESTAMP))::bigint"), SQLDataType.BIGINT)), this, "创建时间（时间戳，秒）");

    /**
     * The column <code>public.client.updated_at</code>. 更新时间（时间戳，秒）
     */
    public final TableField<ClientRecord, Long> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.BIGINT.defaultValue(DSL.field(DSL.raw("(EXTRACT(epoch FROM CURRENT_TIMESTAMP))::bigint"), SQLDataType.BIGINT)), this, "更新时间（时间戳，秒）");

    /**
     * The column <code>public.client.system_prompt</code>.
     */
    public final TableField<ClientRecord, String> SYSTEM_PROMPT = createField(DSL.name("system_prompt"), SQLDataType.VARCHAR(255), this, "");

    private Client(Name alias, Table<ClientRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Client(Name alias, Table<ClientRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("Client表"), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.client</code> table reference
     */
    public Client(String alias) {
        this(DSL.name(alias), CLIENT);
    }

    /**
     * Create an aliased <code>public.client</code> table reference
     */
    public Client(Name alias) {
        this(alias, CLIENT);
    }

    /**
     * Create a <code>public.client</code> table reference
     */
    public Client() {
        this(DSL.name("client"), null);
    }

    public <O extends Record> Client(Table<O> path, ForeignKey<O, ClientRecord> childPath, InverseForeignKey<O, ClientRecord> parentPath) {
        super(path, childPath, parentPath, CLIENT);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ClientPath extends Client implements Path<ClientRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ClientPath(Table<O> path, ForeignKey<O, ClientRecord> childPath, InverseForeignKey<O, ClientRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ClientPath(Name alias, Table<ClientRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ClientPath as(String alias) {
            return new ClientPath(DSL.name(alias), this);
        }

        @Override
        public ClientPath as(Name alias) {
            return new ClientPath(alias, this);
        }

        @Override
        public ClientPath as(Table<?> alias) {
            return new ClientPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<ClientRecord, Long> getIdentity() {
        return (Identity<ClientRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<ClientRecord> getPrimaryKey() {
        return Keys.CLIENT_PKEY;
    }

    private transient AgentClientPath _agentClient;

    /**
     * Get the implicit to-many join path to the
     * <code>public.agent_client</code> table
     */
    public AgentClientPath agentClient() {
        if (_agentClient == null)
            _agentClient = new AgentClientPath(this, null, Keys.AGENT_CLIENT__FK_AGENT_CLIENT_CLIENT.getInverseKey());

        return _agentClient;
    }

    private transient ClientModelPath _clientModel;

    /**
     * Get the implicit to-many join path to the
     * <code>public.client_model</code> table
     */
    public ClientModelPath clientModel() {
        if (_clientModel == null)
            _clientModel = new ClientModelPath(this, null, Keys.CLIENT_MODEL__FK_CLIENT_MODEL_CLIENT.getInverseKey());

        return _clientModel;
    }

    private transient ClientRagPath _clientRag;

    /**
     * Get the implicit to-many join path to the <code>public.client_rag</code>
     * table
     */
    public ClientRagPath clientRag() {
        if (_clientRag == null)
            _clientRag = new ClientRagPath(this, null, Keys.CLIENT_RAG__FK_CLIENT_RAG_CLIENT.getInverseKey());

        return _clientRag;
    }

    /**
     * Get the implicit many-to-many join path to the <code>public.agent</code>
     * table
     */
    public AgentPath agent() {
        return agentClient().agent();
    }

    /**
     * Get the implicit many-to-many join path to the <code>public.model</code>
     * table
     */
    public ModelPath model() {
        return clientModel().model();
    }

    /**
     * Get the implicit many-to-many join path to the <code>public.rag</code>
     * table
     */
    public RagPath rag() {
        return clientRag().rag();
    }

    @Override
    public Client as(String alias) {
        return new Client(DSL.name(alias), this);
    }

    @Override
    public Client as(Name alias) {
        return new Client(alias, this);
    }

    @Override
    public Client as(Table<?> alias) {
        return new Client(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Client rename(String name) {
        return new Client(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Client rename(Name name) {
        return new Client(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Client rename(Table<?> name) {
        return new Client(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Client where(Condition condition) {
        return new Client(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Client where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Client where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Client where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Client where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Client where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Client where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Client where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Client whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Client whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
