/*
 * This file is generated by jOOQ.
 */
package com.example.jooq.tables;


import com.example.jooq.Keys;
import com.example.jooq.Public;
import com.example.jooq.tables.records.ClientMcpRecord;

import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * Client和MCP的关联表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ClientMcp extends TableImpl<ClientMcpRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.client_mcp</code>
     */
    public static final ClientMcp CLIENT_MCP = new ClientMcp();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ClientMcpRecord> getRecordType() {
        return ClientMcpRecord.class;
    }

    /**
     * The column <code>public.client_mcp.client_id</code>. Client ID
     */
    public final TableField<ClientMcpRecord, Long> CLIENT_ID = createField(DSL.name("client_id"), SQLDataType.BIGINT.nullable(false), this, "Client ID");

    /**
     * The column <code>public.client_mcp.mcp_id</code>. MCP ID
     */
    public final TableField<ClientMcpRecord, Long> MCP_ID = createField(DSL.name("mcp_id"), SQLDataType.BIGINT.nullable(false), this, "MCP ID");

    private ClientMcp(Name alias, Table<ClientMcpRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ClientMcp(Name alias, Table<ClientMcpRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("Client和MCP的关联表"), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.client_mcp</code> table reference
     */
    public ClientMcp(String alias) {
        this(DSL.name(alias), CLIENT_MCP);
    }

    /**
     * Create an aliased <code>public.client_mcp</code> table reference
     */
    public ClientMcp(Name alias) {
        this(alias, CLIENT_MCP);
    }

    /**
     * Create a <code>public.client_mcp</code> table reference
     */
    public ClientMcp() {
        this(DSL.name("client_mcp"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<ClientMcpRecord> getPrimaryKey() {
        return Keys.UK_CLIENT_MCP_UNIQUE;
    }

    @Override
    public ClientMcp as(String alias) {
        return new ClientMcp(DSL.name(alias), this);
    }

    @Override
    public ClientMcp as(Name alias) {
        return new ClientMcp(alias, this);
    }

    @Override
    public ClientMcp as(Table<?> alias) {
        return new ClientMcp(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ClientMcp rename(String name) {
        return new ClientMcp(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ClientMcp rename(Name name) {
        return new ClientMcp(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ClientMcp rename(Table<?> name) {
        return new ClientMcp(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ClientMcp where(Condition condition) {
        return new ClientMcp(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ClientMcp where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ClientMcp where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ClientMcp where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ClientMcp where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ClientMcp where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ClientMcp where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ClientMcp where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ClientMcp whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ClientMcp whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
