/*
 * This file is generated by jOOQ.
 */
package com.example.jooq.tables;


import com.example.jooq.Keys;
import com.example.jooq.Public;
import com.example.jooq.tables.Client.ClientPath;
import com.example.jooq.tables.Model.ModelPath;
import com.example.jooq.tables.records.ClientModelRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * Client和Model的关联表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ClientModel extends TableImpl<ClientModelRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.client_model</code>
     */
    public static final ClientModel CLIENT_MODEL = new ClientModel();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ClientModelRecord> getRecordType() {
        return ClientModelRecord.class;
    }

    /**
     * The column <code>public.client_model.client_id</code>. Client ID
     */
    public final TableField<ClientModelRecord, Long> CLIENT_ID = createField(DSL.name("client_id"), SQLDataType.BIGINT.nullable(false), this, "Client ID");

    /**
     * The column <code>public.client_model.model_id</code>. Model ID
     */
    public final TableField<ClientModelRecord, Long> MODEL_ID = createField(DSL.name("model_id"), SQLDataType.BIGINT.nullable(false), this, "Model ID");

    private ClientModel(Name alias, Table<ClientModelRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ClientModel(Name alias, Table<ClientModelRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("Client和Model的关联表"), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.client_model</code> table reference
     */
    public ClientModel(String alias) {
        this(DSL.name(alias), CLIENT_MODEL);
    }

    /**
     * Create an aliased <code>public.client_model</code> table reference
     */
    public ClientModel(Name alias) {
        this(alias, CLIENT_MODEL);
    }

    /**
     * Create a <code>public.client_model</code> table reference
     */
    public ClientModel() {
        this(DSL.name("client_model"), null);
    }

    public <O extends Record> ClientModel(Table<O> path, ForeignKey<O, ClientModelRecord> childPath, InverseForeignKey<O, ClientModelRecord> parentPath) {
        super(path, childPath, parentPath, CLIENT_MODEL);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ClientModelPath extends ClientModel implements Path<ClientModelRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ClientModelPath(Table<O> path, ForeignKey<O, ClientModelRecord> childPath, InverseForeignKey<O, ClientModelRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ClientModelPath(Name alias, Table<ClientModelRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ClientModelPath as(String alias) {
            return new ClientModelPath(DSL.name(alias), this);
        }

        @Override
        public ClientModelPath as(Name alias) {
            return new ClientModelPath(alias, this);
        }

        @Override
        public ClientModelPath as(Table<?> alias) {
            return new ClientModelPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<ClientModelRecord> getPrimaryKey() {
        return Keys.UK_CLIENT_MODEL_UNIQUE;
    }

    @Override
    public List<ForeignKey<ClientModelRecord, ?>> getReferences() {
        return Arrays.asList(Keys.CLIENT_MODEL__FK_CLIENT_MODEL_CLIENT, Keys.CLIENT_MODEL__FK_CLIENT_MODEL_MODEL);
    }

    private transient ClientPath _client;

    /**
     * Get the implicit join path to the <code>public.client</code> table.
     */
    public ClientPath client() {
        if (_client == null)
            _client = new ClientPath(this, Keys.CLIENT_MODEL__FK_CLIENT_MODEL_CLIENT, null);

        return _client;
    }

    private transient ModelPath _model;

    /**
     * Get the implicit join path to the <code>public.model</code> table.
     */
    public ModelPath model() {
        if (_model == null)
            _model = new ModelPath(this, Keys.CLIENT_MODEL__FK_CLIENT_MODEL_MODEL, null);

        return _model;
    }

    @Override
    public ClientModel as(String alias) {
        return new ClientModel(DSL.name(alias), this);
    }

    @Override
    public ClientModel as(Name alias) {
        return new ClientModel(alias, this);
    }

    @Override
    public ClientModel as(Table<?> alias) {
        return new ClientModel(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ClientModel rename(String name) {
        return new ClientModel(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ClientModel rename(Name name) {
        return new ClientModel(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ClientModel rename(Table<?> name) {
        return new ClientModel(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ClientModel where(Condition condition) {
        return new ClientModel(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ClientModel where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ClientModel where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ClientModel where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ClientModel where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ClientModel where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ClientModel where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ClientModel where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ClientModel whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ClientModel whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
