/*
 * This file is generated by jOOQ.
 */
package com.example.jooq.tables;


import com.example.jooq.Keys;
import com.example.jooq.Public;
import com.example.jooq.tables.records.KgEntityRecord;

import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.DefaultDataType;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class KgEntity extends TableImpl<KgEntityRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.kg_entity</code>
     */
    public static final KgEntity KG_ENTITY = new KgEntity();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<KgEntityRecord> getRecordType() {
        return KgEntityRecord.class;
    }

    /**
     * The column <code>public.kg_entity.id</code>.
     */
    public final TableField<KgEntityRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.kg_entity.name</code>.
     */
    public final TableField<KgEntityRecord, String> NAME = createField(DSL.name("name"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.kg_entity.type</code>.
     */
    public final TableField<KgEntityRecord, String> TYPE = createField(DSL.name("type"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.kg_entity.description</code>.
     */
    public final TableField<KgEntityRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.CLOB, this, "");

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    public final TableField<KgEntityRecord, Object> EMBEDDING = createField(DSL.name("embedding"), DefaultDataType.getDefaultDataType("\"public\".\"vector\""), this, "");

    private KgEntity(Name alias, Table<KgEntityRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private KgEntity(Name alias, Table<KgEntityRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.kg_entity</code> table reference
     */
    public KgEntity(String alias) {
        this(DSL.name(alias), KG_ENTITY);
    }

    /**
     * Create an aliased <code>public.kg_entity</code> table reference
     */
    public KgEntity(Name alias) {
        this(alias, KG_ENTITY);
    }

    /**
     * Create a <code>public.kg_entity</code> table reference
     */
    public KgEntity() {
        this(DSL.name("kg_entity"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<KgEntityRecord, Long> getIdentity() {
        return (Identity<KgEntityRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<KgEntityRecord> getPrimaryKey() {
        return Keys.KG_ENTITY_PKEY;
    }

    @Override
    public KgEntity as(String alias) {
        return new KgEntity(DSL.name(alias), this);
    }

    @Override
    public KgEntity as(Name alias) {
        return new KgEntity(alias, this);
    }

    @Override
    public KgEntity as(Table<?> alias) {
        return new KgEntity(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public KgEntity rename(String name) {
        return new KgEntity(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public KgEntity rename(Name name) {
        return new KgEntity(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public KgEntity rename(Table<?> name) {
        return new KgEntity(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public KgEntity where(Condition condition) {
        return new KgEntity(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public KgEntity where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public KgEntity where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public KgEntity where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public KgEntity where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public KgEntity where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public KgEntity where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public KgEntity where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public KgEntity whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public KgEntity whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
