/*
 * This file is generated by jOOQ.
 */
package com.example.jooq.tables;


import com.example.jooq.Keys;
import com.example.jooq.Public;
import com.example.jooq.tables.records.McpRecord;

import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.JSONB;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Mcp extends TableImpl<McpRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.mcp</code>
     */
    public static final Mcp MCP = new Mcp();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<McpRecord> getRecordType() {
        return McpRecord.class;
    }

    /**
     * The column <code>public.mcp.id</code>.
     */
    public final TableField<McpRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.mcp.name</code>.
     */
    public final TableField<McpRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.mcp.type</code>.
     */
    public final TableField<McpRecord, String> TYPE = createField(DSL.name("type"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>public.mcp.description</code>.
     */
    public final TableField<McpRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.mcp.base_url</code>.
     */
    public final TableField<McpRecord, String> BASE_URL = createField(DSL.name("base_url"), SQLDataType.VARCHAR(500), this, "");

    /**
     * The column <code>public.mcp.headers</code>.
     */
    public final TableField<McpRecord, JSONB> HEADERS = createField(DSL.name("headers"), SQLDataType.JSONB, this, "");

    /**
     * The column <code>public.mcp.status</code>.
     */
    public final TableField<McpRecord, String> STATUS = createField(DSL.name("status"), SQLDataType.VARCHAR(50).defaultValue(DSL.field(DSL.raw("'ACTIVE'::character varying"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>public.mcp.created_at</code>.
     */
    public final TableField<McpRecord, Long> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.BIGINT.defaultValue(DSL.field(DSL.raw("(EXTRACT(epoch FROM CURRENT_TIMESTAMP))::bigint"), SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>public.mcp.updated_at</code>.
     */
    public final TableField<McpRecord, Long> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.BIGINT.defaultValue(DSL.field(DSL.raw("(EXTRACT(epoch FROM CURRENT_TIMESTAMP))::bigint"), SQLDataType.BIGINT)), this, "");

    private Mcp(Name alias, Table<McpRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Mcp(Name alias, Table<McpRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.mcp</code> table reference
     */
    public Mcp(String alias) {
        this(DSL.name(alias), MCP);
    }

    /**
     * Create an aliased <code>public.mcp</code> table reference
     */
    public Mcp(Name alias) {
        this(alias, MCP);
    }

    /**
     * Create a <code>public.mcp</code> table reference
     */
    public Mcp() {
        this(DSL.name("mcp"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<McpRecord, Long> getIdentity() {
        return (Identity<McpRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<McpRecord> getPrimaryKey() {
        return Keys.MCP_PKEY;
    }

    @Override
    public Mcp as(String alias) {
        return new Mcp(DSL.name(alias), this);
    }

    @Override
    public Mcp as(Name alias) {
        return new Mcp(alias, this);
    }

    @Override
    public Mcp as(Table<?> alias) {
        return new Mcp(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Mcp rename(String name) {
        return new Mcp(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Mcp rename(Name name) {
        return new Mcp(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Mcp rename(Table<?> name) {
        return new Mcp(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Mcp where(Condition condition) {
        return new Mcp(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Mcp where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Mcp where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Mcp where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Mcp where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Mcp where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Mcp where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Mcp where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Mcp whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Mcp whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
