/*
 * This file is generated by jOOQ.
 */
package com.example.jooq.tables;


import com.example.jooq.Keys;
import com.example.jooq.Public;
import com.example.jooq.tables.Client.ClientPath;
import com.example.jooq.tables.ClientModel.ClientModelPath;
import com.example.jooq.tables.records.ModelRecord;

import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * Model表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Model extends TableImpl<ModelRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.model</code>
     */
    public static final Model MODEL = new Model();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ModelRecord> getRecordType() {
        return ModelRecord.class;
    }

    /**
     * The column <code>public.model.id</code>. 主键ID
     */
    public final TableField<ModelRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "主键ID");

    /**
     * The column <code>public.model.name</code>. Model名称
     */
    public final TableField<ModelRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(255).nullable(false), this, "Model名称");

    /**
     * The column <code>public.model.provider</code>. 提供商：OPENAI, ANTHROPIC,
     * OLLAMA等
     */
    public final TableField<ModelRecord, String> PROVIDER = createField(DSL.name("provider"), SQLDataType.VARCHAR(100).nullable(false), this, "提供商：OPENAI, ANTHROPIC, OLLAMA等");

    /**
     * The column <code>public.model.model_type</code>. 模型类型
     */
    public final TableField<ModelRecord, String> MODEL_TYPE = createField(DSL.name("model_type"), SQLDataType.VARCHAR(100), this, "模型类型");

    /**
     * The column <code>public.model.api_endpoint</code>. API端点
     */
    public final TableField<ModelRecord, String> API_ENDPOINT = createField(DSL.name("api_endpoint"), SQLDataType.VARCHAR(500), this, "API端点");

    /**
     * The column <code>public.model.api_key</code>. API密钥（加密存储）
     */
    public final TableField<ModelRecord, String> API_KEY = createField(DSL.name("api_key"), SQLDataType.VARCHAR(500), this, "API密钥（加密存储）");

    /**
     * The column <code>public.model.max_tokens</code>. 最大token数
     */
    public final TableField<ModelRecord, Integer> MAX_TOKENS = createField(DSL.name("max_tokens"), SQLDataType.INTEGER, this, "最大token数");

    /**
     * The column <code>public.model.temperature</code>. 温度参数
     */
    public final TableField<ModelRecord, Double> TEMPERATURE = createField(DSL.name("temperature"), SQLDataType.DOUBLE.defaultValue(DSL.field(DSL.raw("0.7"), SQLDataType.DOUBLE)), this, "温度参数");

    /**
     * The column <code>public.model.status</code>. 状态：ACTIVE, INACTIVE
     */
    public final TableField<ModelRecord, String> STATUS = createField(DSL.name("status"), SQLDataType.VARCHAR(50).defaultValue(DSL.field(DSL.raw("'ACTIVE'::character varying"), SQLDataType.VARCHAR)), this, "状态：ACTIVE, INACTIVE");

    /**
     * The column <code>public.model.created_at</code>. 创建时间（时间戳，秒）
     */
    public final TableField<ModelRecord, Long> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.BIGINT.defaultValue(DSL.field(DSL.raw("(EXTRACT(epoch FROM CURRENT_TIMESTAMP))::bigint"), SQLDataType.BIGINT)), this, "创建时间（时间戳，秒）");

    /**
     * The column <code>public.model.updated_at</code>. 更新时间（时间戳，秒）
     */
    public final TableField<ModelRecord, Long> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.BIGINT.defaultValue(DSL.field(DSL.raw("(EXTRACT(epoch FROM CURRENT_TIMESTAMP))::bigint"), SQLDataType.BIGINT)), this, "更新时间（时间戳，秒）");

    private Model(Name alias, Table<ModelRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Model(Name alias, Table<ModelRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("Model表"), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.model</code> table reference
     */
    public Model(String alias) {
        this(DSL.name(alias), MODEL);
    }

    /**
     * Create an aliased <code>public.model</code> table reference
     */
    public Model(Name alias) {
        this(alias, MODEL);
    }

    /**
     * Create a <code>public.model</code> table reference
     */
    public Model() {
        this(DSL.name("model"), null);
    }

    public <O extends Record> Model(Table<O> path, ForeignKey<O, ModelRecord> childPath, InverseForeignKey<O, ModelRecord> parentPath) {
        super(path, childPath, parentPath, MODEL);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ModelPath extends Model implements Path<ModelRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ModelPath(Table<O> path, ForeignKey<O, ModelRecord> childPath, InverseForeignKey<O, ModelRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ModelPath(Name alias, Table<ModelRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ModelPath as(String alias) {
            return new ModelPath(DSL.name(alias), this);
        }

        @Override
        public ModelPath as(Name alias) {
            return new ModelPath(alias, this);
        }

        @Override
        public ModelPath as(Table<?> alias) {
            return new ModelPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<ModelRecord, Long> getIdentity() {
        return (Identity<ModelRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<ModelRecord> getPrimaryKey() {
        return Keys.MODEL_PKEY;
    }

    private transient ClientModelPath _clientModel;

    /**
     * Get the implicit to-many join path to the
     * <code>public.client_model</code> table
     */
    public ClientModelPath clientModel() {
        if (_clientModel == null)
            _clientModel = new ClientModelPath(this, null, Keys.CLIENT_MODEL__FK_CLIENT_MODEL_MODEL.getInverseKey());

        return _clientModel;
    }

    /**
     * Get the implicit many-to-many join path to the <code>public.client</code>
     * table
     */
    public ClientPath client() {
        return clientModel().client();
    }

    @Override
    public Model as(String alias) {
        return new Model(DSL.name(alias), this);
    }

    @Override
    public Model as(Name alias) {
        return new Model(alias, this);
    }

    @Override
    public Model as(Table<?> alias) {
        return new Model(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Model rename(String name) {
        return new Model(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Model rename(Name name) {
        return new Model(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Model rename(Table<?> name) {
        return new Model(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Model where(Condition condition) {
        return new Model(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Model where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Model where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Model where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Model where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Model where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Model where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Model where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Model whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Model whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
