/*
 * This file is generated by jOOQ.
 */
package com.example.jooq.tables;


import com.example.jooq.Keys;
import com.example.jooq.Public;
import com.example.jooq.tables.records.OrchestratorMessageRecord;

import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.JSONB;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class OrchestratorMessage extends TableImpl<OrchestratorMessageRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.orchestrator_message</code>
     */
    public static final OrchestratorMessage ORCHESTRATOR_MESSAGE = new OrchestratorMessage();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<OrchestratorMessageRecord> getRecordType() {
        return OrchestratorMessageRecord.class;
    }

    /**
     * The column <code>public.orchestrator_message.id</code>.
     */
    public final TableField<OrchestratorMessageRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.orchestrator_message.run_id</code>.
     */
    public final TableField<OrchestratorMessageRecord, Long> RUN_ID = createField(DSL.name("run_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.orchestrator_message.task_id</code>.
     */
    public final TableField<OrchestratorMessageRecord, String> TASK_ID = createField(DSL.name("task_id"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.orchestrator_message.agent_role</code>.
     */
    public final TableField<OrchestratorMessageRecord, String> AGENT_ROLE = createField(DSL.name("agent_role"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>public.orchestrator_message.message_type</code>.
     */
    public final TableField<OrchestratorMessageRecord, String> MESSAGE_TYPE = createField(DSL.name("message_type"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>public.orchestrator_message.content</code>.
     */
    public final TableField<OrchestratorMessageRecord, String> CONTENT = createField(DSL.name("content"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.orchestrator_message.metadata</code>.
     */
    public final TableField<OrchestratorMessageRecord, JSONB> METADATA = createField(DSL.name("metadata"), SQLDataType.JSONB, this, "");

    /**
     * The column <code>public.orchestrator_message.timestamp</code>.
     */
    public final TableField<OrchestratorMessageRecord, Long> TIMESTAMP = createField(DSL.name("timestamp"), SQLDataType.BIGINT.defaultValue(DSL.field(DSL.raw("(EXTRACT(epoch FROM CURRENT_TIMESTAMP))::bigint"), SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>public.orchestrator_message.sequence</code>.
     */
    public final TableField<OrchestratorMessageRecord, Integer> SEQUENCE = createField(DSL.name("sequence"), SQLDataType.INTEGER, this, "");

    private OrchestratorMessage(Name alias, Table<OrchestratorMessageRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private OrchestratorMessage(Name alias, Table<OrchestratorMessageRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.orchestrator_message</code> table
     * reference
     */
    public OrchestratorMessage(String alias) {
        this(DSL.name(alias), ORCHESTRATOR_MESSAGE);
    }

    /**
     * Create an aliased <code>public.orchestrator_message</code> table
     * reference
     */
    public OrchestratorMessage(Name alias) {
        this(alias, ORCHESTRATOR_MESSAGE);
    }

    /**
     * Create a <code>public.orchestrator_message</code> table reference
     */
    public OrchestratorMessage() {
        this(DSL.name("orchestrator_message"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<OrchestratorMessageRecord, Long> getIdentity() {
        return (Identity<OrchestratorMessageRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<OrchestratorMessageRecord> getPrimaryKey() {
        return Keys.ORCHESTRATOR_MESSAGE_PKEY;
    }

    @Override
    public OrchestratorMessage as(String alias) {
        return new OrchestratorMessage(DSL.name(alias), this);
    }

    @Override
    public OrchestratorMessage as(Name alias) {
        return new OrchestratorMessage(alias, this);
    }

    @Override
    public OrchestratorMessage as(Table<?> alias) {
        return new OrchestratorMessage(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public OrchestratorMessage rename(String name) {
        return new OrchestratorMessage(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public OrchestratorMessage rename(Name name) {
        return new OrchestratorMessage(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public OrchestratorMessage rename(Table<?> name) {
        return new OrchestratorMessage(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OrchestratorMessage where(Condition condition) {
        return new OrchestratorMessage(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OrchestratorMessage where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OrchestratorMessage where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OrchestratorMessage where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public OrchestratorMessage where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public OrchestratorMessage where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public OrchestratorMessage where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public OrchestratorMessage where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OrchestratorMessage whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OrchestratorMessage whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
