/*
 * This file is generated by jOOQ.
 */
package com.example.jooq.tables;


import com.example.jooq.Indexes;
import com.example.jooq.Keys;
import com.example.jooq.Public;
import com.example.jooq.tables.Agent.AgentPath;
import com.example.jooq.tables.Orchestrator.OrchestratorPath;
import com.example.jooq.tables.records.OrchestratorAgentRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * Orchestrator与Agent的关联表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class OrchestratorAgent extends TableImpl<OrchestratorAgentRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.orchestrator_agent</code>
     */
    public static final OrchestratorAgent ORCHESTRATOR_AGENT = new OrchestratorAgent();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<OrchestratorAgentRecord> getRecordType() {
        return OrchestratorAgentRecord.class;
    }

    /**
     * The column <code>public.orchestrator_agent.orchestrator_id</code>.
     */
    public final TableField<OrchestratorAgentRecord, Long> ORCHESTRATOR_ID = createField(DSL.name("orchestrator_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.orchestrator_agent.agent_id</code>.
     */
    public final TableField<OrchestratorAgentRecord, Long> AGENT_ID = createField(DSL.name("agent_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.orchestrator_agent.seq</code>.
     * Agent在Orchestrator中的执行顺序
     */
    public final TableField<OrchestratorAgentRecord, Integer> SEQ = createField(DSL.name("seq"), SQLDataType.INTEGER, this, "Agent在Orchestrator中的执行顺序");

    /**
     * The column <code>public.orchestrator_agent.role</code>.
     * Agent角色代码：1=supervisor, 2=worker
     */
    public final TableField<OrchestratorAgentRecord, Long> ROLE = createField(DSL.name("role"), SQLDataType.BIGINT, this, "Agent角色代码：1=supervisor, 2=worker");

    private OrchestratorAgent(Name alias, Table<OrchestratorAgentRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private OrchestratorAgent(Name alias, Table<OrchestratorAgentRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("Orchestrator与Agent的关联表"), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.orchestrator_agent</code> table reference
     */
    public OrchestratorAgent(String alias) {
        this(DSL.name(alias), ORCHESTRATOR_AGENT);
    }

    /**
     * Create an aliased <code>public.orchestrator_agent</code> table reference
     */
    public OrchestratorAgent(Name alias) {
        this(alias, ORCHESTRATOR_AGENT);
    }

    /**
     * Create a <code>public.orchestrator_agent</code> table reference
     */
    public OrchestratorAgent() {
        this(DSL.name("orchestrator_agent"), null);
    }

    public <O extends Record> OrchestratorAgent(Table<O> path, ForeignKey<O, OrchestratorAgentRecord> childPath, InverseForeignKey<O, OrchestratorAgentRecord> parentPath) {
        super(path, childPath, parentPath, ORCHESTRATOR_AGENT);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class OrchestratorAgentPath extends OrchestratorAgent implements Path<OrchestratorAgentRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> OrchestratorAgentPath(Table<O> path, ForeignKey<O, OrchestratorAgentRecord> childPath, InverseForeignKey<O, OrchestratorAgentRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private OrchestratorAgentPath(Name alias, Table<OrchestratorAgentRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public OrchestratorAgentPath as(String alias) {
            return new OrchestratorAgentPath(DSL.name(alias), this);
        }

        @Override
        public OrchestratorAgentPath as(Name alias) {
            return new OrchestratorAgentPath(alias, this);
        }

        @Override
        public OrchestratorAgentPath as(Table<?> alias) {
            return new OrchestratorAgentPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_ORCHESTRATOR_AGENT_AGENT_ID, Indexes.IDX_ORCHESTRATOR_AGENT_ORCHESTRATOR_ID, Indexes.IDX_ORCHESTRATOR_AGENT_SEQ);
    }

    @Override
    public UniqueKey<OrchestratorAgentRecord> getPrimaryKey() {
        return Keys.PK_ORCHESTRATOR_AGENT;
    }

    @Override
    public List<ForeignKey<OrchestratorAgentRecord, ?>> getReferences() {
        return Arrays.asList(Keys.ORCHESTRATOR_AGENT__FK_ORCHESTRATOR_AGENT_AGENT, Keys.ORCHESTRATOR_AGENT__FK_ORCHESTRATOR_AGENT_ORCHESTRATOR);
    }

    private transient AgentPath _agent;

    /**
     * Get the implicit join path to the <code>public.agent</code> table.
     */
    public AgentPath agent() {
        if (_agent == null)
            _agent = new AgentPath(this, Keys.ORCHESTRATOR_AGENT__FK_ORCHESTRATOR_AGENT_AGENT, null);

        return _agent;
    }

    private transient OrchestratorPath _orchestrator;

    /**
     * Get the implicit join path to the <code>public.orchestrator</code> table.
     */
    public OrchestratorPath orchestrator() {
        if (_orchestrator == null)
            _orchestrator = new OrchestratorPath(this, Keys.ORCHESTRATOR_AGENT__FK_ORCHESTRATOR_AGENT_ORCHESTRATOR, null);

        return _orchestrator;
    }

    @Override
    public OrchestratorAgent as(String alias) {
        return new OrchestratorAgent(DSL.name(alias), this);
    }

    @Override
    public OrchestratorAgent as(Name alias) {
        return new OrchestratorAgent(alias, this);
    }

    @Override
    public OrchestratorAgent as(Table<?> alias) {
        return new OrchestratorAgent(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public OrchestratorAgent rename(String name) {
        return new OrchestratorAgent(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public OrchestratorAgent rename(Name name) {
        return new OrchestratorAgent(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public OrchestratorAgent rename(Table<?> name) {
        return new OrchestratorAgent(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OrchestratorAgent where(Condition condition) {
        return new OrchestratorAgent(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OrchestratorAgent where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OrchestratorAgent where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OrchestratorAgent where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public OrchestratorAgent where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public OrchestratorAgent where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public OrchestratorAgent where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public OrchestratorAgent where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OrchestratorAgent whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OrchestratorAgent whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
