/*
 * This file is generated by jOOQ.
 */
package com.example.jooq.tables;


import com.example.jooq.Keys;
import com.example.jooq.Public;
import com.example.jooq.tables.records.OrchestratorRunRecord;

import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.JSONB;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class OrchestratorRun extends TableImpl<OrchestratorRunRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.orchestrator_run</code>
     */
    public static final OrchestratorRun ORCHESTRATOR_RUN = new OrchestratorRun();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<OrchestratorRunRecord> getRecordType() {
        return OrchestratorRunRecord.class;
    }

    /**
     * The column <code>public.orchestrator_run.id</code>.
     */
    public final TableField<OrchestratorRunRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.orchestrator_run.orchestrator_id</code>.
     */
    public final TableField<OrchestratorRunRecord, Long> ORCHESTRATOR_ID = createField(DSL.name("orchestrator_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.orchestrator_run.session_id</code>.
     */
    public final TableField<OrchestratorRunRecord, String> SESSION_ID = createField(DSL.name("session_id"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.orchestrator_run.user_id</code>.
     */
    public final TableField<OrchestratorRunRecord, String> USER_ID = createField(DSL.name("user_id"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.orchestrator_run.goal</code>.
     */
    public final TableField<OrchestratorRunRecord, String> GOAL = createField(DSL.name("goal"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.orchestrator_run.status</code>.
     */
    public final TableField<OrchestratorRunRecord, String> STATUS = createField(DSL.name("status"), SQLDataType.VARCHAR(50).defaultValue(DSL.field(DSL.raw("'RUNNING'::character varying"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>public.orchestrator_run.start_time</code>.
     */
    public final TableField<OrchestratorRunRecord, Long> START_TIME = createField(DSL.name("start_time"), SQLDataType.BIGINT.defaultValue(DSL.field(DSL.raw("(EXTRACT(epoch FROM CURRENT_TIMESTAMP))::bigint"), SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>public.orchestrator_run.end_time</code>.
     */
    public final TableField<OrchestratorRunRecord, Long> END_TIME = createField(DSL.name("end_time"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.orchestrator_run.total_tasks</code>.
     */
    public final TableField<OrchestratorRunRecord, Integer> TOTAL_TASKS = createField(DSL.name("total_tasks"), SQLDataType.INTEGER.defaultValue(DSL.field(DSL.raw("0"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.orchestrator_run.completed_tasks</code>.
     */
    public final TableField<OrchestratorRunRecord, Integer> COMPLETED_TASKS = createField(DSL.name("completed_tasks"), SQLDataType.INTEGER.defaultValue(DSL.field(DSL.raw("0"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.orchestrator_run.execution_mode</code>.
     */
    public final TableField<OrchestratorRunRecord, String> EXECUTION_MODE = createField(DSL.name("execution_mode"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>public.orchestrator_run.metadata</code>.
     */
    public final TableField<OrchestratorRunRecord, JSONB> METADATA = createField(DSL.name("metadata"), SQLDataType.JSONB, this, "");

    /**
     * The column <code>public.orchestrator_run.created_at</code>.
     */
    public final TableField<OrchestratorRunRecord, Long> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.BIGINT.defaultValue(DSL.field(DSL.raw("(EXTRACT(epoch FROM CURRENT_TIMESTAMP))::bigint"), SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>public.orchestrator_run.updated_at</code>.
     */
    public final TableField<OrchestratorRunRecord, Long> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.BIGINT.defaultValue(DSL.field(DSL.raw("(EXTRACT(epoch FROM CURRENT_TIMESTAMP))::bigint"), SQLDataType.BIGINT)), this, "");

    private OrchestratorRun(Name alias, Table<OrchestratorRunRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private OrchestratorRun(Name alias, Table<OrchestratorRunRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.orchestrator_run</code> table reference
     */
    public OrchestratorRun(String alias) {
        this(DSL.name(alias), ORCHESTRATOR_RUN);
    }

    /**
     * Create an aliased <code>public.orchestrator_run</code> table reference
     */
    public OrchestratorRun(Name alias) {
        this(alias, ORCHESTRATOR_RUN);
    }

    /**
     * Create a <code>public.orchestrator_run</code> table reference
     */
    public OrchestratorRun() {
        this(DSL.name("orchestrator_run"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<OrchestratorRunRecord, Long> getIdentity() {
        return (Identity<OrchestratorRunRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<OrchestratorRunRecord> getPrimaryKey() {
        return Keys.ORCHESTRATOR_RUN_PKEY;
    }

    @Override
    public OrchestratorRun as(String alias) {
        return new OrchestratorRun(DSL.name(alias), this);
    }

    @Override
    public OrchestratorRun as(Name alias) {
        return new OrchestratorRun(alias, this);
    }

    @Override
    public OrchestratorRun as(Table<?> alias) {
        return new OrchestratorRun(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public OrchestratorRun rename(String name) {
        return new OrchestratorRun(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public OrchestratorRun rename(Name name) {
        return new OrchestratorRun(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public OrchestratorRun rename(Table<?> name) {
        return new OrchestratorRun(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OrchestratorRun where(Condition condition) {
        return new OrchestratorRun(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OrchestratorRun where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OrchestratorRun where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OrchestratorRun where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public OrchestratorRun where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public OrchestratorRun where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public OrchestratorRun where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public OrchestratorRun where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OrchestratorRun whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OrchestratorRun whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
