/*
 * This file is generated by jOOQ.
 */
package com.example.jooq.tables;


import com.example.jooq.Keys;
import com.example.jooq.Public;
import com.example.jooq.tables.records.OrchestratorRecord;

import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Orchestrator extends TableImpl<OrchestratorRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.orchestrator</code>
     */
    public static final Orchestrator ORCHESTRATOR = new Orchestrator();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<OrchestratorRecord> getRecordType() {
        return OrchestratorRecord.class;
    }

    /**
     * The column <code>public.orchestrator.id</code>.
     */
    public final TableField<OrchestratorRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.orchestrator.name</code>.
     */
    public final TableField<OrchestratorRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.orchestrator.description</code>.
     */
    public final TableField<OrchestratorRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.orchestrator.status</code>.
     */
    public final TableField<OrchestratorRecord, String> STATUS = createField(DSL.name("status"), SQLDataType.VARCHAR(50).defaultValue(DSL.field(DSL.raw("'ACTIVE'::character varying"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>public.orchestrator.created_at</code>.
     */
    public final TableField<OrchestratorRecord, Long> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.BIGINT.defaultValue(DSL.field(DSL.raw("(EXTRACT(epoch FROM CURRENT_TIMESTAMP))::bigint"), SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>public.orchestrator.updated_at</code>.
     */
    public final TableField<OrchestratorRecord, Long> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.BIGINT.defaultValue(DSL.field(DSL.raw("(EXTRACT(epoch FROM CURRENT_TIMESTAMP))::bigint"), SQLDataType.BIGINT)), this, "");

    private Orchestrator(Name alias, Table<OrchestratorRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Orchestrator(Name alias, Table<OrchestratorRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.orchestrator</code> table reference
     */
    public Orchestrator(String alias) {
        this(DSL.name(alias), ORCHESTRATOR);
    }

    /**
     * Create an aliased <code>public.orchestrator</code> table reference
     */
    public Orchestrator(Name alias) {
        this(alias, ORCHESTRATOR);
    }

    /**
     * Create a <code>public.orchestrator</code> table reference
     */
    public Orchestrator() {
        this(DSL.name("orchestrator"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<OrchestratorRecord, Long> getIdentity() {
        return (Identity<OrchestratorRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<OrchestratorRecord> getPrimaryKey() {
        return Keys.ORCHESTRATOR_PKEY;
    }

    @Override
    public Orchestrator as(String alias) {
        return new Orchestrator(DSL.name(alias), this);
    }

    @Override
    public Orchestrator as(Name alias) {
        return new Orchestrator(alias, this);
    }

    @Override
    public Orchestrator as(Table<?> alias) {
        return new Orchestrator(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Orchestrator rename(String name) {
        return new Orchestrator(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Orchestrator rename(Name name) {
        return new Orchestrator(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Orchestrator rename(Table<?> name) {
        return new Orchestrator(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Orchestrator where(Condition condition) {
        return new Orchestrator(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Orchestrator where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Orchestrator where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Orchestrator where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Orchestrator where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Orchestrator where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Orchestrator where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Orchestrator where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Orchestrator whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Orchestrator whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
