/*
 * This file is generated by jOOQ.
 */
package com.example.jooq.tables;


import com.example.jooq.Indexes;
import com.example.jooq.Keys;
import com.example.jooq.Public;
import com.example.jooq.tables.Agent.AgentPath;
import com.example.jooq.tables.AgentRag.AgentRagPath;
import com.example.jooq.tables.records.RagRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.JSONB;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * RAG表（Retrieval-Augmented Generation）
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Rag extends TableImpl<RagRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.rag</code>
     */
    public static final Rag RAG = new Rag();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RagRecord> getRecordType() {
        return RagRecord.class;
    }

    /**
     * The column <code>public.rag.id</code>.
     */
    public final TableField<RagRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.rag.name</code>.
     */
    public final TableField<RagRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.rag.vector_store_type</code>.
     */
    public final TableField<RagRecord, String> VECTOR_STORE_TYPE = createField(DSL.name("vector_store_type"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>public.rag.embedding_model</code>.
     */
    public final TableField<RagRecord, String> EMBEDDING_MODEL = createField(DSL.name("embedding_model"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.rag.chunk_size</code>.
     */
    public final TableField<RagRecord, Integer> CHUNK_SIZE = createField(DSL.name("chunk_size"), SQLDataType.INTEGER.defaultValue(DSL.field(DSL.raw("1000"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.rag.chunk_overlap</code>.
     */
    public final TableField<RagRecord, Integer> CHUNK_OVERLAP = createField(DSL.name("chunk_overlap"), SQLDataType.INTEGER.defaultValue(DSL.field(DSL.raw("200"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.rag.database_type</code>.
     */
    public final TableField<RagRecord, String> DATABASE_TYPE = createField(DSL.name("database_type"), SQLDataType.VARCHAR(50).defaultValue(DSL.field(DSL.raw("'POSTGRESQL'::character varying"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>public.rag.database_host</code>.
     */
    public final TableField<RagRecord, String> DATABASE_HOST = createField(DSL.name("database_host"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.rag.database_port</code>.
     */
    public final TableField<RagRecord, Integer> DATABASE_PORT = createField(DSL.name("database_port"), SQLDataType.INTEGER.defaultValue(DSL.field(DSL.raw("5432"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.rag.database_name</code>.
     */
    public final TableField<RagRecord, String> DATABASE_NAME = createField(DSL.name("database_name"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.rag.database_user</code>.
     */
    public final TableField<RagRecord, String> DATABASE_USER = createField(DSL.name("database_user"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.rag.database_password</code>.
     */
    public final TableField<RagRecord, String> DATABASE_PASSWORD = createField(DSL.name("database_password"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.rag.table_name</code>.
     */
    public final TableField<RagRecord, String> TABLE_NAME = createField(DSL.name("table_name"), SQLDataType.VARCHAR(255).defaultValue(DSL.field(DSL.raw("'vector_document'::character varying"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>public.rag.dimension</code>.
     */
    public final TableField<RagRecord, Integer> DIMENSION = createField(DSL.name("dimension"), SQLDataType.INTEGER.defaultValue(DSL.field(DSL.raw("1536"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.rag.use_index</code>.
     */
    public final TableField<RagRecord, Boolean> USE_INDEX = createField(DSL.name("use_index"), SQLDataType.BOOLEAN.defaultValue(DSL.field(DSL.raw("true"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>public.rag.index_list_size</code>.
     */
    public final TableField<RagRecord, Integer> INDEX_LIST_SIZE = createField(DSL.name("index_list_size"), SQLDataType.INTEGER.defaultValue(DSL.field(DSL.raw("1000"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.rag.config</code>. RAG配置信息（JSON格式）
     */
    public final TableField<RagRecord, JSONB> CONFIG = createField(DSL.name("config"), SQLDataType.JSONB, this, "RAG配置信息（JSON格式）");

    /**
     * The column <code>public.rag.status</code>.
     */
    public final TableField<RagRecord, String> STATUS = createField(DSL.name("status"), SQLDataType.VARCHAR(50).defaultValue(DSL.field(DSL.raw("'ACTIVE'::character varying"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>public.rag.created_at</code>.
     */
    public final TableField<RagRecord, Long> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.BIGINT.defaultValue(DSL.field(DSL.raw("(EXTRACT(epoch FROM CURRENT_TIMESTAMP))::bigint"), SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>public.rag.updated_at</code>.
     */
    public final TableField<RagRecord, Long> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.BIGINT.defaultValue(DSL.field(DSL.raw("(EXTRACT(epoch FROM CURRENT_TIMESTAMP))::bigint"), SQLDataType.BIGINT)), this, "");

    private Rag(Name alias, Table<RagRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Rag(Name alias, Table<RagRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("RAG表（Retrieval-Augmented Generation）"), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.rag</code> table reference
     */
    public Rag(String alias) {
        this(DSL.name(alias), RAG);
    }

    /**
     * Create an aliased <code>public.rag</code> table reference
     */
    public Rag(Name alias) {
        this(alias, RAG);
    }

    /**
     * Create a <code>public.rag</code> table reference
     */
    public Rag() {
        this(DSL.name("rag"), null);
    }

    public <O extends Record> Rag(Table<O> path, ForeignKey<O, RagRecord> childPath, InverseForeignKey<O, RagRecord> parentPath) {
        super(path, childPath, parentPath, RAG);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class RagPath extends Rag implements Path<RagRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> RagPath(Table<O> path, ForeignKey<O, RagRecord> childPath, InverseForeignKey<O, RagRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private RagPath(Name alias, Table<RagRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public RagPath as(String alias) {
            return new RagPath(DSL.name(alias), this);
        }

        @Override
        public RagPath as(Name alias) {
            return new RagPath(alias, this);
        }

        @Override
        public RagPath as(Table<?> alias) {
            return new RagPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_RAG_STATUS, Indexes.IDX_RAG_VECTOR_STORE_TYPE);
    }

    @Override
    public Identity<RagRecord, Long> getIdentity() {
        return (Identity<RagRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<RagRecord> getPrimaryKey() {
        return Keys.RAG_PKEY;
    }

    private transient AgentRagPath _agentRag;

    /**
     * Get the implicit to-many join path to the <code>public.agent_rag</code>
     * table
     */
    public AgentRagPath agentRag() {
        if (_agentRag == null)
            _agentRag = new AgentRagPath(this, null, Keys.AGENT_RAG__FK_AGENT_RAG_RAG.getInverseKey());

        return _agentRag;
    }

    /**
     * Get the implicit many-to-many join path to the <code>public.agent</code>
     * table
     */
    public AgentPath agent() {
        return agentRag().agent();
    }

    @Override
    public Rag as(String alias) {
        return new Rag(DSL.name(alias), this);
    }

    @Override
    public Rag as(Name alias) {
        return new Rag(alias, this);
    }

    @Override
    public Rag as(Table<?> alias) {
        return new Rag(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Rag rename(String name) {
        return new Rag(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Rag rename(Name name) {
        return new Rag(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Rag rename(Table<?> name) {
        return new Rag(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Rag where(Condition condition) {
        return new Rag(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Rag where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Rag where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Rag where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Rag where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Rag where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Rag where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Rag where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Rag whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Rag whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
