/*
 * This file is generated by jOOQ.
 */
package com.example.jooq.tables;


import com.example.jooq.Indexes;
import com.example.jooq.Keys;
import com.example.jooq.Public;
import com.example.jooq.tables.records.VectorDocumentRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Index;
import org.jooq.JSON;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.DefaultDataType;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class VectorDocument extends TableImpl<VectorDocumentRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.vector_document</code>
     */
    public static final VectorDocument VECTOR_DOCUMENT = new VectorDocument();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VectorDocumentRecord> getRecordType() {
        return VectorDocumentRecord.class;
    }

    /**
     * The column <code>public.vector_document.embedding_id</code>.
     */
    public final TableField<VectorDocumentRecord, UUID> EMBEDDING_ID = createField(DSL.name("embedding_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    public final TableField<VectorDocumentRecord, Object> EMBEDDING = createField(DSL.name("embedding"), DefaultDataType.getDefaultDataType("\"public\".\"vector\""), this, "");

    /**
     * The column <code>public.vector_document.text</code>.
     */
    public final TableField<VectorDocumentRecord, String> TEXT = createField(DSL.name("text"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.vector_document.metadata</code>.
     */
    public final TableField<VectorDocumentRecord, JSON> METADATA = createField(DSL.name("metadata"), SQLDataType.JSON, this, "");

    private VectorDocument(Name alias, Table<VectorDocumentRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private VectorDocument(Name alias, Table<VectorDocumentRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.vector_document</code> table reference
     */
    public VectorDocument(String alias) {
        this(DSL.name(alias), VECTOR_DOCUMENT);
    }

    /**
     * Create an aliased <code>public.vector_document</code> table reference
     */
    public VectorDocument(Name alias) {
        this(alias, VECTOR_DOCUMENT);
    }

    /**
     * Create a <code>public.vector_document</code> table reference
     */
    public VectorDocument() {
        this(DSL.name("vector_document"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.VECTOR_DOCUMENT_IVFFLAT_INDEX);
    }

    @Override
    public UniqueKey<VectorDocumentRecord> getPrimaryKey() {
        return Keys.VECTOR_DOCUMENT_PKEY;
    }

    @Override
    public VectorDocument as(String alias) {
        return new VectorDocument(DSL.name(alias), this);
    }

    @Override
    public VectorDocument as(Name alias) {
        return new VectorDocument(alias, this);
    }

    @Override
    public VectorDocument as(Table<?> alias) {
        return new VectorDocument(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public VectorDocument rename(String name) {
        return new VectorDocument(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public VectorDocument rename(Name name) {
        return new VectorDocument(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public VectorDocument rename(Table<?> name) {
        return new VectorDocument(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VectorDocument where(Condition condition) {
        return new VectorDocument(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VectorDocument where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VectorDocument where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VectorDocument where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VectorDocument where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VectorDocument where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VectorDocument where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VectorDocument where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VectorDocument whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VectorDocument whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
