/*
 * This file is generated by jOOQ.
 */
package com.example.jooq.tables.records;


import com.example.jooq.tables.AgentMemory;

import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * Agent共享记忆表，支持会话级和全局级别的记忆存储
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AgentMemoryRecord extends UpdatableRecordImpl<AgentMemoryRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.agent_memory.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.agent_memory.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.agent_memory.session_id</code>. 会话ID，为空表示全局记忆
     */
    public void setSessionId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.agent_memory.session_id</code>. 会话ID，为空表示全局记忆
     */
    public String getSessionId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.agent_memory.agent_id</code>. Agent
     * ID，为空表示所有Agent共享
     */
    public void setAgentId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.agent_memory.agent_id</code>. Agent
     * ID，为空表示所有Agent共享
     */
    public Long getAgentId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.agent_memory.memory_key</code>. 记忆键
     */
    public void setMemoryKey(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.agent_memory.memory_key</code>. 记忆键
     */
    public String getMemoryKey() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.agent_memory.memory_value</code>. 记忆值
     */
    public void setMemoryValue(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.agent_memory.memory_value</code>. 记忆值
     */
    public String getMemoryValue() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.agent_memory.memory_type</code>. 记忆类型
     */
    public void setMemoryType(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.agent_memory.memory_type</code>. 记忆类型
     */
    public String getMemoryType() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.agent_memory.tags</code>. 标签数组
     */
    public void setTags(String[] value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.agent_memory.tags</code>. 标签数组
     */
    public String[] getTags() {
        return (String[]) get(6);
    }

    /**
     * Setter for <code>public.agent_memory.expires_at</code>. 过期时间戳
     */
    public void setExpiresAt(Long value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.agent_memory.expires_at</code>. 过期时间戳
     */
    public Long getExpiresAt() {
        return (Long) get(7);
    }

    /**
     * Setter for <code>public.agent_memory.metadata</code>.
     */
    public void setMetadata(JSONB value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.agent_memory.metadata</code>.
     */
    public JSONB getMetadata() {
        return (JSONB) get(8);
    }

    /**
     * Setter for <code>public.agent_memory.created_at</code>.
     */
    public void setCreatedAt(Long value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.agent_memory.created_at</code>.
     */
    public Long getCreatedAt() {
        return (Long) get(9);
    }

    /**
     * Setter for <code>public.agent_memory.updated_at</code>.
     */
    public void setUpdatedAt(Long value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.agent_memory.updated_at</code>.
     */
    public Long getUpdatedAt() {
        return (Long) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AgentMemoryRecord
     */
    public AgentMemoryRecord() {
        super(AgentMemory.AGENT_MEMORY);
    }

    /**
     * Create a detached, initialised AgentMemoryRecord
     */
    public AgentMemoryRecord(Long id, String sessionId, Long agentId, String memoryKey, String memoryValue, String memoryType, String[] tags, Long expiresAt, JSONB metadata, Long createdAt, Long updatedAt) {
        super(AgentMemory.AGENT_MEMORY);

        setId(id);
        setSessionId(sessionId);
        setAgentId(agentId);
        setMemoryKey(memoryKey);
        setMemoryValue(memoryValue);
        setMemoryType(memoryType);
        setTags(tags);
        setExpiresAt(expiresAt);
        setMetadata(metadata);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        resetChangedOnNotNull();
    }
}
