/*
 * This file is generated by jOOQ.
 */
package com.example.jooq.tables.records;


import com.example.jooq.tables.Agent;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AgentRecord extends UpdatableRecordImpl<AgentRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.agent.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.agent.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.agent.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.agent.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.agent.description</code>.
     */
    public void setDescription(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.agent.description</code>.
     */
    public String getDescription() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.agent.status</code>.
     */
    public void setStatus(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.agent.status</code>.
     */
    public String getStatus() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.agent.created_at</code>.
     */
    public void setCreatedAt(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.agent.created_at</code>.
     */
    public Long getCreatedAt() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>public.agent.updated_at</code>.
     */
    public void setUpdatedAt(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.agent.updated_at</code>.
     */
    public Long getUpdatedAt() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>public.agent.system_prompt</code>.
     */
    public void setSystemPrompt(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.agent.system_prompt</code>.
     */
    public String getSystemPrompt() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AgentRecord
     */
    public AgentRecord() {
        super(Agent.AGENT);
    }

    /**
     * Create a detached, initialised AgentRecord
     */
    public AgentRecord(Long id, String name, String description, String status, Long createdAt, Long updatedAt, String systemPrompt) {
        super(Agent.AGENT);

        setId(id);
        setName(name);
        setDescription(description);
        setStatus(status);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        setSystemPrompt(systemPrompt);
        resetChangedOnNotNull();
    }
}
