/*
 * This file is generated by jOOQ.
 */
package com.example.jooq.tables.records;


import com.example.jooq.tables.AgentRag;

import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AgentRagRecord extends UpdatableRecordImpl<AgentRagRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.agent_rag.agent_id</code>.
     */
    public void setAgentId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.agent_rag.agent_id</code>.
     */
    public Long getAgentId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.agent_rag.rag_id</code>.
     */
    public void setRagId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.agent_rag.rag_id</code>.
     */
    public Long getRagId() {
        return (Long) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Long, Long> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AgentRagRecord
     */
    public AgentRagRecord() {
        super(AgentRag.AGENT_RAG);
    }

    /**
     * Create a detached, initialised AgentRagRecord
     */
    public AgentRagRecord(Long agentId, Long ragId) {
        super(AgentRag.AGENT_RAG);

        setAgentId(agentId);
        setRagId(ragId);
        resetChangedOnNotNull();
    }
}
