/*
 * This file is generated by jOOQ.
 */
package com.example.jooq.tables.records;


import com.example.jooq.tables.AgentClient;

import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * Agent和Client的关联表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AgentClientRecord extends UpdatableRecordImpl<AgentClientRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.agent_client.agent_id</code>. Agent ID
     */
    public void setAgentId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.agent_client.agent_id</code>. Agent ID
     */
    public Long getAgentId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.agent_client.client_id</code>. Client ID
     */
    public void setClientId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.agent_client.client_id</code>. Client ID
     */
    public Long getClientId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.agent_client.seq</code>.
     */
    public void setSeq(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.agent_client.seq</code>.
     */
    public Integer getSeq() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.agent_client.role</code>. Client角色代码：1=supervisor, 2=worker
     */
    public void setRole(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.agent_client.role</code>. Client角色代码：1=supervisor, 2=worker
     */
    public Long getRole() {
        return (Long) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Long, Long> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AgentClientRecord
     */
    public AgentClientRecord() {
        super(AgentClient.AGENT_CLIENT);
    }

    /**
     * Create a detached, initialised AgentClientRecord
     */
    public AgentClientRecord(Long agentId, Long clientId, Integer seq) {
        super(AgentClient.AGENT_CLIENT);

        setAgentId(agentId);
        setClientId(clientId);
        setSeq(seq);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised AgentClientRecord
     */
    public AgentClientRecord(Long agentId, Long clientId, Integer seq, Long role) {
        super(AgentClient.AGENT_CLIENT);

        setAgentId(agentId);
        setClientId(clientId);
        setSeq(seq);
        setRole(role);
        resetChangedOnNotNull();
    }
}
