/*
 * This file is generated by jOOQ.
 */
package com.example.jooq.tables.records;


import com.example.jooq.tables.AgentModel;

import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AgentModelRecord extends UpdatableRecordImpl<AgentModelRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.agent_model.agent_id</code>.
     */
    public void setAgentId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.agent_model.agent_id</code>.
     */
    public Long getAgentId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.agent_model.model_id</code>.
     */
    public void setModelId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.agent_model.model_id</code>.
     */
    public Long getModelId() {
        return (Long) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Long, Long> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AgentModelRecord
     */
    public AgentModelRecord() {
        super(AgentModel.AGENT_MODEL);
    }

    /**
     * Create a detached, initialised AgentModelRecord
     */
    public AgentModelRecord(Long agentId, Long modelId) {
        super(AgentModel.AGENT_MODEL);

        setAgentId(agentId);
        setModelId(modelId);
        resetChangedOnNotNull();
    }
}
