/*
 * This file is generated by jOOQ.
 */
package com.example.jooq.tables.records;


import com.example.jooq.tables.AgentMcp;

import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AgentMcpRecord extends UpdatableRecordImpl<AgentMcpRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.agent_mcp.agent_id</code>.
     */
    public void setAgentId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.agent_mcp.agent_id</code>.
     */
    public Long getAgentId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.agent_mcp.mcp_id</code>.
     */
    public void setMcpId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.agent_mcp.mcp_id</code>.
     */
    public Long getMcpId() {
        return (Long) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Long, Long> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AgentMcpRecord
     */
    public AgentMcpRecord() {
        super(AgentMcp.AGENT_MCP);
    }

    /**
     * Create a detached, initialised AgentMcpRecord
     */
    public AgentMcpRecord(Long agentId, Long mcpId) {
        super(AgentMcp.AGENT_MCP);

        setAgentId(agentId);
        setMcpId(mcpId);
        resetChangedOnNotNull();
    }
}
