/*
 * This file is generated by jOOQ.
 */
package com.example.jooq.tables.records;


import com.example.jooq.tables.ClientMcp;

import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * Client和MCP的关联表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ClientMcpRecord extends UpdatableRecordImpl<ClientMcpRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.client_mcp.client_id</code>. Client ID
     */
    public void setClientId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.client_mcp.client_id</code>. Client ID
     */
    public Long getClientId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.client_mcp.mcp_id</code>. MCP ID
     */
    public void setMcpId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.client_mcp.mcp_id</code>. MCP ID
     */
    public Long getMcpId() {
        return (Long) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Long, Long> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ClientMcpRecord
     */
    public ClientMcpRecord() {
        super(ClientMcp.CLIENT_MCP);
    }

    /**
     * Create a detached, initialised ClientMcpRecord
     */
    public ClientMcpRecord(Long clientId, Long mcpId) {
        super(ClientMcp.CLIENT_MCP);

        setClientId(clientId);
        setMcpId(mcpId);
        resetChangedOnNotNull();
    }
}
