/*
 * This file is generated by jOOQ.
 */
package com.example.jooq.tables.records;


import com.example.jooq.tables.ClientModel;

import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * Client和Model的关联表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ClientModelRecord extends UpdatableRecordImpl<ClientModelRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.client_model.client_id</code>. Client ID
     */
    public void setClientId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.client_model.client_id</code>. Client ID
     */
    public Long getClientId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.client_model.model_id</code>. Model ID
     */
    public void setModelId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.client_model.model_id</code>. Model ID
     */
    public Long getModelId() {
        return (Long) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Long, Long> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ClientModelRecord
     */
    public ClientModelRecord() {
        super(ClientModel.CLIENT_MODEL);
    }

    /**
     * Create a detached, initialised ClientModelRecord
     */
    public ClientModelRecord(Long clientId, Long modelId) {
        super(ClientModel.CLIENT_MODEL);

        setClientId(clientId);
        setModelId(modelId);
        resetChangedOnNotNull();
    }
}
