/*
 * This file is generated by jOOQ.
 */
package com.example.jooq.tables.records;


import com.example.jooq.tables.ClientRag;

import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * Client和RAG的关联表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ClientRagRecord extends UpdatableRecordImpl<ClientRagRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.client_rag.client_id</code>. Client ID
     */
    public void setClientId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.client_rag.client_id</code>. Client ID
     */
    public Long getClientId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.client_rag.rag_id</code>. RAG ID
     */
    public void setRagId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.client_rag.rag_id</code>. RAG ID
     */
    public Long getRagId() {
        return (Long) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Long, Long> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ClientRagRecord
     */
    public ClientRagRecord() {
        super(ClientRag.CLIENT_RAG);
    }

    /**
     * Create a detached, initialised ClientRagRecord
     */
    public ClientRagRecord(Long clientId, Long ragId) {
        super(ClientRag.CLIENT_RAG);

        setClientId(clientId);
        setRagId(ragId);
        resetChangedOnNotNull();
    }
}
