/*
 * This file is generated by jOOQ.
 */
package com.example.jooq.tables.records;


import com.example.jooq.tables.Client;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * Client表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ClientRecord extends UpdatableRecordImpl<ClientRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.client.id</code>. 主键ID
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.client.id</code>. 主键ID
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.client.name</code>. Client名称
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.client.name</code>. Client名称
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.client.description</code>. Client描述
     */
    public void setDescription(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.client.description</code>. Client描述
     */
    public String getDescription() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.client.status</code>. 状态：ACTIVE, INACTIVE
     */
    public void setStatus(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.client.status</code>. 状态：ACTIVE, INACTIVE
     */
    public String getStatus() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.client.created_at</code>. 创建时间（时间戳，秒）
     */
    public void setCreatedAt(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.client.created_at</code>. 创建时间（时间戳，秒）
     */
    public Long getCreatedAt() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>public.client.updated_at</code>. 更新时间（时间戳，秒）
     */
    public void setUpdatedAt(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.client.updated_at</code>. 更新时间（时间戳，秒）
     */
    public Long getUpdatedAt() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>public.client.system_prompt</code>.
     */
    public void setSystemPrompt(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.client.system_prompt</code>.
     */
    public String getSystemPrompt() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ClientRecord
     */
    public ClientRecord() {
        super(Client.CLIENT);
    }

    /**
     * Create a detached, initialised ClientRecord
     */
    public ClientRecord(Long id, String name, String description, String status, Long createdAt, Long updatedAt, String systemPrompt) {
        super(Client.CLIENT);

        setId(id);
        setName(name);
        setDescription(description);
        setStatus(status);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        setSystemPrompt(systemPrompt);
        resetChangedOnNotNull();
    }
}
