/*
 * This file is generated by jOOQ.
 */
package com.example.jooq.tables.records;


import com.example.jooq.tables.Doc;

import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class DocRecord extends TableRecordImpl<DocRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.doc.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.doc.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.doc.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.doc.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.doc.owner</code>.
     */
    public void setOwner(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.doc.owner</code>.
     */
    public String getOwner() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.doc.text</code>.
     */
    public void setText(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.doc.text</code>.
     */
    public String getText() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.doc.type</code>.
     */
    public void setType(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.doc.type</code>.
     */
    public Integer getType() {
        return (Integer) get(4);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DocRecord
     */
    public DocRecord() {
        super(Doc.DOC);
    }

    /**
     * Create a detached, initialised DocRecord
     */
    public DocRecord(String id, String name, String owner, String text, Integer type) {
        super(Doc.DOC);

        setId(id);
        setName(name);
        setOwner(owner);
        setText(text);
        setType(type);
        resetChangedOnNotNull();
    }
}
