/*
 * This file is generated by jOOQ.
 */
package com.example.jooq.tables.records;


import com.example.jooq.tables.Mcp;

import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * MCP表（Model Context Protocol）
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class McpRecord extends UpdatableRecordImpl<McpRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.mcp.id</code>. 主键ID
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.mcp.id</code>. 主键ID
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.mcp.name</code>. MCP名称
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.mcp.name</code>. MCP名称
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.mcp.type</code>. MCP类型
     */
    public void setType(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.mcp.type</code>. MCP类型
     */
    public String getType() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.mcp.endpoint</code>. MCP端点
     */
    public void setEndpoint(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.mcp.endpoint</code>. MCP端点
     */
    public String getEndpoint() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.mcp.config</code>. MCP配置信息（JSON格式）
     */
    public void setConfig(JSONB value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.mcp.config</code>. MCP配置信息（JSON格式）
     */
    public JSONB getConfig() {
        return (JSONB) get(4);
    }

    /**
     * Setter for <code>public.mcp.status</code>. 状态：ACTIVE, INACTIVE
     */
    public void setStatus(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.mcp.status</code>. 状态：ACTIVE, INACTIVE
     */
    public String getStatus() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.mcp.created_at</code>. 创建时间（时间戳，秒）
     */
    public void setCreatedAt(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.mcp.created_at</code>. 创建时间（时间戳，秒）
     */
    public Long getCreatedAt() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>public.mcp.updated_at</code>. 更新时间（时间戳，秒）
     */
    public void setUpdatedAt(Long value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.mcp.updated_at</code>. 更新时间（时间戳，秒）
     */
    public Long getUpdatedAt() {
        return (Long) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached McpRecord
     */
    public McpRecord() {
        super(Mcp.MCP);
    }

    /**
     * Create a detached, initialised McpRecord
     */
    public McpRecord(Long id, String name, String type, String endpoint, JSONB config, String status, Long createdAt, Long updatedAt) {
        super(Mcp.MCP);

        setId(id);
        setName(name);
        setType(type);
        setEndpoint(endpoint);
        setConfig(config);
        setStatus(status);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        resetChangedOnNotNull();
    }
}
