/*
 * This file is generated by jOOQ.
 */
package com.example.jooq.tables.records;


import com.example.jooq.tables.Model;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * Model表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ModelRecord extends UpdatableRecordImpl<ModelRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.model.id</code>. 主键ID
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.model.id</code>. 主键ID
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.model.name</code>. Model名称
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.model.name</code>. Model名称
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.model.provider</code>. 提供商：OPENAI, ANTHROPIC,
     * OLLAMA等
     */
    public void setProvider(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.model.provider</code>. 提供商：OPENAI, ANTHROPIC,
     * OLLAMA等
     */
    public String getProvider() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.model.model_type</code>. 模型类型
     */
    public void setModelType(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.model.model_type</code>. 模型类型
     */
    public String getModelType() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.model.api_endpoint</code>. API端点
     */
    public void setApiEndpoint(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.model.api_endpoint</code>. API端点
     */
    public String getApiEndpoint() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.model.api_key</code>. API密钥（加密存储）
     */
    public void setApiKey(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.model.api_key</code>. API密钥（加密存储）
     */
    public String getApiKey() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.model.max_tokens</code>. 最大token数
     */
    public void setMaxTokens(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.model.max_tokens</code>. 最大token数
     */
    public Integer getMaxTokens() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>public.model.temperature</code>. 温度参数
     */
    public void setTemperature(Double value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.model.temperature</code>. 温度参数
     */
    public Double getTemperature() {
        return (Double) get(7);
    }

    /**
     * Setter for <code>public.model.status</code>. 状态：ACTIVE, INACTIVE
     */
    public void setStatus(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.model.status</code>. 状态：ACTIVE, INACTIVE
     */
    public String getStatus() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.model.created_at</code>. 创建时间（时间戳，秒）
     */
    public void setCreatedAt(Long value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.model.created_at</code>. 创建时间（时间戳，秒）
     */
    public Long getCreatedAt() {
        return (Long) get(9);
    }

    /**
     * Setter for <code>public.model.updated_at</code>. 更新时间（时间戳，秒）
     */
    public void setUpdatedAt(Long value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.model.updated_at</code>. 更新时间（时间戳，秒）
     */
    public Long getUpdatedAt() {
        return (Long) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ModelRecord
     */
    public ModelRecord() {
        super(Model.MODEL);
    }

    /**
     * Create a detached, initialised ModelRecord
     */
    public ModelRecord(Long id, String name, String provider, String modelType, String apiEndpoint, String apiKey, Integer maxTokens, Double temperature, String status, Long createdAt, Long updatedAt) {
        super(Model.MODEL);

        setId(id);
        setName(name);
        setProvider(provider);
        setModelType(modelType);
        setApiEndpoint(apiEndpoint);
        setApiKey(apiKey);
        setMaxTokens(maxTokens);
        setTemperature(temperature);
        setStatus(status);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        resetChangedOnNotNull();
    }
}
