/*
 * This file is generated by jOOQ.
 */
package com.example.jooq.tables.records;


import com.example.jooq.tables.OrchestratorMessage;

import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * Orchestrator消息记录表，记录所有Agent间的交互信息
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class OrchestratorMessageRecord extends UpdatableRecordImpl<OrchestratorMessageRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.orchestrator_message.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.orchestrator_message.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.orchestrator_message.run_id</code>. 关联的执行会话ID
     */
    public void setRunId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.orchestrator_message.run_id</code>. 关联的执行会话ID
     */
    public Long getRunId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.orchestrator_message.task_id</code>. 任务ID
     */
    public void setTaskId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.orchestrator_message.task_id</code>. 任务ID
     */
    public String getTaskId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.orchestrator_message.agent_role</code>. Agent角色
     */
    public void setAgentRole(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.orchestrator_message.agent_role</code>. Agent角色
     */
    public String getAgentRole() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.orchestrator_message.message_type</code>. 消息类型
     */
    public void setMessageType(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.orchestrator_message.message_type</code>. 消息类型
     */
    public String getMessageType() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.orchestrator_message.content</code>. 消息内容
     */
    public void setContent(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.orchestrator_message.content</code>. 消息内容
     */
    public String getContent() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.orchestrator_message.metadata</code>.
     * 消息元数据（tokens消耗、成本、耗时等）
     */
    public void setMetadata(JSONB value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.orchestrator_message.metadata</code>.
     * 消息元数据（tokens消耗、成本、耗时等）
     */
    public JSONB getMetadata() {
        return (JSONB) get(6);
    }

    /**
     * Setter for <code>public.orchestrator_message.timestamp</code>.
     */
    public void setTimestamp(Long value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.orchestrator_message.timestamp</code>.
     */
    public Long getTimestamp() {
        return (Long) get(7);
    }

    /**
     * Setter for <code>public.orchestrator_message.sequence</code>. 消息序列号
     */
    public void setSequence(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.orchestrator_message.sequence</code>. 消息序列号
     */
    public Integer getSequence() {
        return (Integer) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OrchestratorMessageRecord
     */
    public OrchestratorMessageRecord() {
        super(OrchestratorMessage.ORCHESTRATOR_MESSAGE);
    }

    /**
     * Create a detached, initialised OrchestratorMessageRecord
     */
    public OrchestratorMessageRecord(Long id, Long runId, String taskId, String agentRole, String messageType, String content, JSONB metadata, Long timestamp, Integer sequence) {
        super(OrchestratorMessage.ORCHESTRATOR_MESSAGE);

        setId(id);
        setRunId(runId);
        setTaskId(taskId);
        setAgentRole(agentRole);
        setMessageType(messageType);
        setContent(content);
        setMetadata(metadata);
        setTimestamp(timestamp);
        setSequence(sequence);
        resetChangedOnNotNull();
    }
}
