/*
 * This file is generated by jOOQ.
 */
package com.example.jooq.tables.records;


import com.example.jooq.tables.OrchestratorRun;

import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class OrchestratorRunRecord extends UpdatableRecordImpl<OrchestratorRunRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.orchestrator_run.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.orchestrator_run.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.orchestrator_run.orchestrator_id</code>.
     */
    public void setOrchestratorId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.orchestrator_run.orchestrator_id</code>.
     */
    public Long getOrchestratorId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.orchestrator_run.session_id</code>.
     */
    public void setSessionId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.orchestrator_run.session_id</code>.
     */
    public String getSessionId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.orchestrator_run.user_id</code>.
     */
    public void setUserId(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.orchestrator_run.user_id</code>.
     */
    public String getUserId() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.orchestrator_run.goal</code>.
     */
    public void setGoal(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.orchestrator_run.goal</code>.
     */
    public String getGoal() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.orchestrator_run.status</code>.
     */
    public void setStatus(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.orchestrator_run.status</code>.
     */
    public String getStatus() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.orchestrator_run.start_time</code>.
     */
    public void setStartTime(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.orchestrator_run.start_time</code>.
     */
    public Long getStartTime() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>public.orchestrator_run.end_time</code>.
     */
    public void setEndTime(Long value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.orchestrator_run.end_time</code>.
     */
    public Long getEndTime() {
        return (Long) get(7);
    }

    /**
     * Setter for <code>public.orchestrator_run.total_tasks</code>.
     */
    public void setTotalTasks(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.orchestrator_run.total_tasks</code>.
     */
    public Integer getTotalTasks() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>public.orchestrator_run.completed_tasks</code>.
     */
    public void setCompletedTasks(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.orchestrator_run.completed_tasks</code>.
     */
    public Integer getCompletedTasks() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>public.orchestrator_run.execution_mode</code>.
     */
    public void setExecutionMode(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.orchestrator_run.execution_mode</code>.
     */
    public String getExecutionMode() {
        return (String) get(10);
    }

    /**
     * Setter for <code>public.orchestrator_run.metadata</code>.
     */
    public void setMetadata(JSONB value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.orchestrator_run.metadata</code>.
     */
    public JSONB getMetadata() {
        return (JSONB) get(11);
    }

    /**
     * Setter for <code>public.orchestrator_run.created_at</code>.
     */
    public void setCreatedAt(Long value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.orchestrator_run.created_at</code>.
     */
    public Long getCreatedAt() {
        return (Long) get(12);
    }

    /**
     * Setter for <code>public.orchestrator_run.updated_at</code>.
     */
    public void setUpdatedAt(Long value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.orchestrator_run.updated_at</code>.
     */
    public Long getUpdatedAt() {
        return (Long) get(13);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OrchestratorRunRecord
     */
    public OrchestratorRunRecord() {
        super(OrchestratorRun.ORCHESTRATOR_RUN);
    }

    /**
     * Create a detached, initialised OrchestratorRunRecord
     */
    public OrchestratorRunRecord(Long id, Long orchestratorId, String sessionId, String userId, String goal, String status, Long startTime, Long endTime, Integer totalTasks, Integer completedTasks, String executionMode, JSONB metadata, Long createdAt, Long updatedAt) {
        super(OrchestratorRun.ORCHESTRATOR_RUN);

        setId(id);
        setOrchestratorId(orchestratorId);
        setSessionId(sessionId);
        setUserId(userId);
        setGoal(goal);
        setStatus(status);
        setStartTime(startTime);
        setEndTime(endTime);
        setTotalTasks(totalTasks);
        setCompletedTasks(completedTasks);
        setExecutionMode(executionMode);
        setMetadata(metadata);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        resetChangedOnNotNull();
    }
}
