/*
 * This file is generated by jOOQ.
 */
package com.example.jooq.tables.records;


import com.example.jooq.tables.Rag;

import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * RAG表（Retrieval-Augmented Generation）
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class RagRecord extends UpdatableRecordImpl<RagRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.rag.id</code>. 主键ID
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.rag.id</code>. 主键ID
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.rag.name</code>. RAG名称
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.rag.name</code>. RAG名称
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.rag.vector_store_type</code>. 向量存储类型
     */
    public void setVectorStoreType(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.rag.vector_store_type</code>. 向量存储类型
     */
    public String getVectorStoreType() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.rag.embedding_model</code>. 嵌入模型
     */
    public void setEmbeddingModel(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.rag.embedding_model</code>. 嵌入模型
     */
    public String getEmbeddingModel() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.rag.chunk_size</code>. 分块大小
     */
    public void setChunkSize(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.rag.chunk_size</code>. 分块大小
     */
    public Integer getChunkSize() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>public.rag.chunk_overlap</code>. 分块重叠大小
     */
    public void setChunkOverlap(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.rag.chunk_overlap</code>. 分块重叠大小
     */
    public Integer getChunkOverlap() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>public.rag.database_type</code>. 数据库类型：POSTGRESQL,
     * MYSQL等
     */
    public void setDatabaseType(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.rag.database_type</code>. 数据库类型：POSTGRESQL,
     * MYSQL等
     */
    public String getDatabaseType() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.rag.database_host</code>. 数据库主机地址
     */
    public void setDatabaseHost(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.rag.database_host</code>. 数据库主机地址
     */
    public String getDatabaseHost() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.rag.database_port</code>. 数据库端口
     */
    public void setDatabasePort(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.rag.database_port</code>. 数据库端口
     */
    public Integer getDatabasePort() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>public.rag.database_name</code>. 数据库名称
     */
    public void setDatabaseName(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.rag.database_name</code>. 数据库名称
     */
    public String getDatabaseName() {
        return (String) get(9);
    }

    /**
     * Setter for <code>public.rag.database_user</code>. 数据库用户名
     */
    public void setDatabaseUser(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.rag.database_user</code>. 数据库用户名
     */
    public String getDatabaseUser() {
        return (String) get(10);
    }

    /**
     * Setter for <code>public.rag.database_password</code>. 数据库密码
     */
    public void setDatabasePassword(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.rag.database_password</code>. 数据库密码
     */
    public String getDatabasePassword() {
        return (String) get(11);
    }

    /**
     * Setter for <code>public.rag.table_name</code>. 向量存储表名
     */
    public void setTableName(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.rag.table_name</code>. 向量存储表名
     */
    public String getTableName() {
        return (String) get(12);
    }

    /**
     * Setter for <code>public.rag.dimension</code>. 向量维度
     */
    public void setDimension(Integer value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.rag.dimension</code>. 向量维度
     */
    public Integer getDimension() {
        return (Integer) get(13);
    }

    /**
     * Setter for <code>public.rag.use_index</code>. 是否使用索引
     */
    public void setUseIndex(Boolean value) {
        set(14, value);
    }

    /**
     * Getter for <code>public.rag.use_index</code>. 是否使用索引
     */
    public Boolean getUseIndex() {
        return (Boolean) get(14);
    }

    /**
     * Setter for <code>public.rag.index_list_size</code>. 索引列表大小
     */
    public void setIndexListSize(Integer value) {
        set(15, value);
    }

    /**
     * Getter for <code>public.rag.index_list_size</code>. 索引列表大小
     */
    public Integer getIndexListSize() {
        return (Integer) get(15);
    }

    /**
     * Setter for <code>public.rag.config</code>. RAG配置信息（JSON格式，扩展配置）
     */
    public void setConfig(JSONB value) {
        set(16, value);
    }

    /**
     * Getter for <code>public.rag.config</code>. RAG配置信息（JSON格式，扩展配置）
     */
    public JSONB getConfig() {
        return (JSONB) get(16);
    }

    /**
     * Setter for <code>public.rag.status</code>. 状态：ACTIVE, INACTIVE
     */
    public void setStatus(String value) {
        set(17, value);
    }

    /**
     * Getter for <code>public.rag.status</code>. 状态：ACTIVE, INACTIVE
     */
    public String getStatus() {
        return (String) get(17);
    }

    /**
     * Setter for <code>public.rag.created_at</code>. 创建时间（时间戳，秒）
     */
    public void setCreatedAt(Long value) {
        set(18, value);
    }

    /**
     * Getter for <code>public.rag.created_at</code>. 创建时间（时间戳，秒）
     */
    public Long getCreatedAt() {
        return (Long) get(18);
    }

    /**
     * Setter for <code>public.rag.updated_at</code>. 更新时间（时间戳，秒）
     */
    public void setUpdatedAt(Long value) {
        set(19, value);
    }

    /**
     * Getter for <code>public.rag.updated_at</code>. 更新时间（时间戳，秒）
     */
    public Long getUpdatedAt() {
        return (Long) get(19);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RagRecord
     */
    public RagRecord() {
        super(Rag.RAG);
    }

    /**
     * Create a detached, initialised RagRecord
     */
    public RagRecord(Long id, String name, String vectorStoreType, String embeddingModel, Integer chunkSize, Integer chunkOverlap, String databaseType, String databaseHost, Integer databasePort, String databaseName, String databaseUser, String databasePassword, String tableName, Integer dimension, Boolean useIndex, Integer indexListSize, JSONB config, String status, Long createdAt, Long updatedAt) {
        super(Rag.RAG);

        setId(id);
        setName(name);
        setVectorStoreType(vectorStoreType);
        setEmbeddingModel(embeddingModel);
        setChunkSize(chunkSize);
        setChunkOverlap(chunkOverlap);
        setDatabaseType(databaseType);
        setDatabaseHost(databaseHost);
        setDatabasePort(databasePort);
        setDatabaseName(databaseName);
        setDatabaseUser(databaseUser);
        setDatabasePassword(databasePassword);
        setTableName(tableName);
        setDimension(dimension);
        setUseIndex(useIndex);
        setIndexListSize(indexListSize);
        setConfig(config);
        setStatus(status);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        resetChangedOnNotNull();
    }
}
