/*
 * This file is generated by jOOQ.
 */
package com.example.jooq.tables.records;


import com.example.jooq.tables.Rag;

import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * RAG表（Retrieval-Augmented Generation）
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class RagRecord extends UpdatableRecordImpl<RagRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.rag.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.rag.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.rag.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.rag.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.rag.vector_store_type</code>.
     */
    public void setVectorStoreType(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.rag.vector_store_type</code>.
     */
    public String getVectorStoreType() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.rag.embedding_model</code>.
     */
    public void setEmbeddingModel(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.rag.embedding_model</code>.
     */
    public String getEmbeddingModel() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.rag.chunk_size</code>.
     */
    public void setChunkSize(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.rag.chunk_size</code>.
     */
    public Integer getChunkSize() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>public.rag.chunk_overlap</code>.
     */
    public void setChunkOverlap(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.rag.chunk_overlap</code>.
     */
    public Integer getChunkOverlap() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>public.rag.database_type</code>.
     */
    public void setDatabaseType(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.rag.database_type</code>.
     */
    public String getDatabaseType() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.rag.database_host</code>.
     */
    public void setDatabaseHost(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.rag.database_host</code>.
     */
    public String getDatabaseHost() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.rag.database_port</code>.
     */
    public void setDatabasePort(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.rag.database_port</code>.
     */
    public Integer getDatabasePort() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>public.rag.database_name</code>.
     */
    public void setDatabaseName(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.rag.database_name</code>.
     */
    public String getDatabaseName() {
        return (String) get(9);
    }

    /**
     * Setter for <code>public.rag.database_user</code>.
     */
    public void setDatabaseUser(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.rag.database_user</code>.
     */
    public String getDatabaseUser() {
        return (String) get(10);
    }

    /**
     * Setter for <code>public.rag.database_password</code>.
     */
    public void setDatabasePassword(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.rag.database_password</code>.
     */
    public String getDatabasePassword() {
        return (String) get(11);
    }

    /**
     * Setter for <code>public.rag.table_name</code>.
     */
    public void setTableName(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.rag.table_name</code>.
     */
    public String getTableName() {
        return (String) get(12);
    }

    /**
     * Setter for <code>public.rag.dimension</code>.
     */
    public void setDimension(Integer value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.rag.dimension</code>.
     */
    public Integer getDimension() {
        return (Integer) get(13);
    }

    /**
     * Setter for <code>public.rag.use_index</code>.
     */
    public void setUseIndex(Boolean value) {
        set(14, value);
    }

    /**
     * Getter for <code>public.rag.use_index</code>.
     */
    public Boolean getUseIndex() {
        return (Boolean) get(14);
    }

    /**
     * Setter for <code>public.rag.index_list_size</code>.
     */
    public void setIndexListSize(Integer value) {
        set(15, value);
    }

    /**
     * Getter for <code>public.rag.index_list_size</code>.
     */
    public Integer getIndexListSize() {
        return (Integer) get(15);
    }

    /**
     * Setter for <code>public.rag.config</code>. RAG配置信息（JSON格式）
     */
    public void setConfig(JSONB value) {
        set(16, value);
    }

    /**
     * Getter for <code>public.rag.config</code>. RAG配置信息（JSON格式）
     */
    public JSONB getConfig() {
        return (JSONB) get(16);
    }

    /**
     * Setter for <code>public.rag.status</code>.
     */
    public void setStatus(String value) {
        set(17, value);
    }

    /**
     * Getter for <code>public.rag.status</code>.
     */
    public String getStatus() {
        return (String) get(17);
    }

    /**
     * Setter for <code>public.rag.created_at</code>.
     */
    public void setCreatedAt(Long value) {
        set(18, value);
    }

    /**
     * Getter for <code>public.rag.created_at</code>.
     */
    public Long getCreatedAt() {
        return (Long) get(18);
    }

    /**
     * Setter for <code>public.rag.updated_at</code>.
     */
    public void setUpdatedAt(Long value) {
        set(19, value);
    }

    /**
     * Getter for <code>public.rag.updated_at</code>.
     */
    public Long getUpdatedAt() {
        return (Long) get(19);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RagRecord
     */
    public RagRecord() {
        super(Rag.RAG);
    }

    /**
     * Create a detached, initialised RagRecord
     */
    public RagRecord(Long id, String name, String vectorStoreType, String embeddingModel, Integer chunkSize, Integer chunkOverlap, String databaseType, String databaseHost, Integer databasePort, String databaseName, String databaseUser, String databasePassword, String tableName, Integer dimension, Boolean useIndex, Integer indexListSize, JSONB config, String status, Long createdAt, Long updatedAt) {
        super(Rag.RAG);

        setId(id);
        setName(name);
        setVectorStoreType(vectorStoreType);
        setEmbeddingModel(embeddingModel);
        setChunkSize(chunkSize);
        setChunkOverlap(chunkOverlap);
        setDatabaseType(databaseType);
        setDatabaseHost(databaseHost);
        setDatabasePort(databasePort);
        setDatabaseName(databaseName);
        setDatabaseUser(databaseUser);
        setDatabasePassword(databasePassword);
        setTableName(tableName);
        setDimension(dimension);
        setUseIndex(useIndex);
        setIndexListSize(indexListSize);
        setConfig(config);
        setStatus(status);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        resetChangedOnNotNull();
    }
}
