/*
 * This file is generated by jOOQ.
 */
package com.example.jooq.tables.records;


import com.example.jooq.tables.VectorDocument;

import java.util.UUID;

import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class VectorDocumentRecord extends UpdatableRecordImpl<VectorDocumentRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.vector_document.embedding_id</code>.
     */
    public void setEmbeddingId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.vector_document.embedding_id</code>.
     */
    public UUID getEmbeddingId() {
        return (UUID) get(0);
    }

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    public void setEmbedding(Object value) {
        set(1, value);
    }

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    public Object getEmbedding() {
        return get(1);
    }

    /**
     * Setter for <code>public.vector_document.text</code>.
     */
    public void setText(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.vector_document.text</code>.
     */
    public String getText() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.vector_document.metadata</code>.
     */
    public void setMetadata(JSONB value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.vector_document.metadata</code>.
     */
    public JSONB getMetadata() {
        return (JSONB) get(3);
    }

    /**
     * Setter for <code>public.vector_document.rag_id</code>.
     */
    public void setRagId(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.vector_document.rag_id</code>.
     */
    public Long getRagId() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>public.vector_document.chunk_index</code>.
     */
    public void setChunkIndex(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.vector_document.chunk_index</code>.
     */
    public Integer getChunkIndex() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>public.vector_document.created_at</code>.
     */
    public void setCreatedAt(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.vector_document.created_at</code>.
     */
    public Long getCreatedAt() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>public.vector_document.updated_at</code>.
     */
    public void setUpdatedAt(Long value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.vector_document.updated_at</code>.
     */
    public Long getUpdatedAt() {
        return (Long) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VectorDocumentRecord
     */
    public VectorDocumentRecord() {
        super(VectorDocument.VECTOR_DOCUMENT);
    }

    /**
     * Create a detached, initialised VectorDocumentRecord
     */
    public VectorDocumentRecord(UUID embeddingId, Object embedding, String text, JSONB metadata, Long ragId, Integer chunkIndex, Long createdAt, Long updatedAt) {
        super(VectorDocument.VECTOR_DOCUMENT);

        setEmbeddingId(embeddingId);
        setEmbedding(embedding);
        setText(text);
        setMetadata(metadata);
        setRagId(ragId);
        setChunkIndex(chunkIndex);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        resetChangedOnNotNull();
    }
}
