/*
 * This file is generated by jOOQ.
 */
package com.example.jooq.tables.records;


import com.example.jooq.tables.VectorDocument;

import java.util.UUID;

import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 存储向量嵌入数据的表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class VectorDocumentRecord extends UpdatableRecordImpl<VectorDocumentRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.vector_document.embedding_id</code>. 向量文档ID（UUID）
     */
    public void setEmbeddingId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.vector_document.embedding_id</code>. 向量文档ID（UUID）
     */
    public UUID getEmbeddingId() {
        return (UUID) get(0);
    }

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    public void setEmbedding(Object value) {
        set(1, value);
    }

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    public Object getEmbedding() {
        return get(1);
    }

    /**
     * Setter for <code>public.vector_document.text</code>. 原始文本内容
     */
    public void setText(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.vector_document.text</code>. 原始文本内容
     */
    public String getText() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.vector_document.metadata</code>. 元信息（JSON格式）
     */
    public void setMetadata(JSONB value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.vector_document.metadata</code>. 元信息（JSON格式）
     */
    public JSONB getMetadata() {
        return (JSONB) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VectorDocumentRecord
     */
    public VectorDocumentRecord() {
        super(VectorDocument.VECTOR_DOCUMENT);
    }

    /**
     * Create a detached, initialised VectorDocumentRecord
     */
    public VectorDocumentRecord(UUID embeddingId, Object embedding, String text, JSONB metadata) {
        super(VectorDocument.VECTOR_DOCUMENT);

        setEmbeddingId(embeddingId);
        setEmbedding(embedding);
        setText(text);
        setMetadata(metadata);
        resetChangedOnNotNull();
    }
}
