/*
 * This file is generated by jOOQ.
 */
package com.example.jooq;


import com.example.jooq.tables.Agent;
import com.example.jooq.tables.AgentClient;
import com.example.jooq.tables.Client;
import com.example.jooq.tables.ClientMcp;
import com.example.jooq.tables.ClientModel;
import com.example.jooq.tables.ClientRag;
import com.example.jooq.tables.Mcp;
import com.example.jooq.tables.Model;
import com.example.jooq.tables.Rag;
import com.example.jooq.tables.VectorDocument;
import com.example.jooq.tables.records.AgentClientRecord;
import com.example.jooq.tables.records.AgentRecord;
import com.example.jooq.tables.records.ClientMcpRecord;
import com.example.jooq.tables.records.ClientModelRecord;
import com.example.jooq.tables.records.ClientRagRecord;
import com.example.jooq.tables.records.ClientRecord;
import com.example.jooq.tables.records.McpRecord;
import com.example.jooq.tables.records.ModelRecord;
import com.example.jooq.tables.records.RagRecord;
import com.example.jooq.tables.records.VectorDocumentRecord;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AgentRecord> AGENT_PKEY = Internal.createUniqueKey(Agent.AGENT, DSL.name("agent_pkey"), new TableField[] { Agent.AGENT.ID }, true);
    public static final UniqueKey<AgentClientRecord> UK_AGENT_CLIENT_UNIQUE = Internal.createUniqueKey(AgentClient.AGENT_CLIENT, DSL.name("uk_agent_client_unique"), new TableField[] { AgentClient.AGENT_CLIENT.AGENT_ID, AgentClient.AGENT_CLIENT.CLIENT_ID }, true);
    public static final UniqueKey<ClientRecord> CLIENT_PKEY = Internal.createUniqueKey(Client.CLIENT, DSL.name("client_pkey"), new TableField[] { Client.CLIENT.ID }, true);
    public static final UniqueKey<ClientMcpRecord> UK_CLIENT_MCP_UNIQUE = Internal.createUniqueKey(ClientMcp.CLIENT_MCP, DSL.name("uk_client_mcp_unique"), new TableField[] { ClientMcp.CLIENT_MCP.CLIENT_ID, ClientMcp.CLIENT_MCP.MCP_ID }, true);
    public static final UniqueKey<ClientModelRecord> UK_CLIENT_MODEL_UNIQUE = Internal.createUniqueKey(ClientModel.CLIENT_MODEL, DSL.name("uk_client_model_unique"), new TableField[] { ClientModel.CLIENT_MODEL.CLIENT_ID, ClientModel.CLIENT_MODEL.MODEL_ID }, true);
    public static final UniqueKey<ClientRagRecord> UK_CLIENT_RAG_UNIQUE = Internal.createUniqueKey(ClientRag.CLIENT_RAG, DSL.name("uk_client_rag_unique"), new TableField[] { ClientRag.CLIENT_RAG.CLIENT_ID, ClientRag.CLIENT_RAG.RAG_ID }, true);
    public static final UniqueKey<McpRecord> MCP_PKEY = Internal.createUniqueKey(Mcp.MCP, DSL.name("mcp_pkey"), new TableField[] { Mcp.MCP.ID }, true);
    public static final UniqueKey<ModelRecord> MODEL_PKEY = Internal.createUniqueKey(Model.MODEL, DSL.name("model_pkey"), new TableField[] { Model.MODEL.ID }, true);
    public static final UniqueKey<RagRecord> RAG_PKEY = Internal.createUniqueKey(Rag.RAG, DSL.name("rag_pkey"), new TableField[] { Rag.RAG.ID }, true);
    public static final UniqueKey<VectorDocumentRecord> VECTOR_DOCUMENT_PKEY = Internal.createUniqueKey(VectorDocument.VECTOR_DOCUMENT, DSL.name("vector_document_pkey"), new TableField[] { VectorDocument.VECTOR_DOCUMENT.EMBEDDING_ID }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<AgentClientRecord, AgentRecord> AGENT_CLIENT__FK_AGENT_CLIENT_AGENT = Internal.createForeignKey(AgentClient.AGENT_CLIENT, DSL.name("fk_agent_client_agent"), new TableField[] { AgentClient.AGENT_CLIENT.AGENT_ID }, Keys.AGENT_PKEY, new TableField[] { Agent.AGENT.ID }, true);
    public static final ForeignKey<AgentClientRecord, ClientRecord> AGENT_CLIENT__FK_AGENT_CLIENT_CLIENT = Internal.createForeignKey(AgentClient.AGENT_CLIENT, DSL.name("fk_agent_client_client"), new TableField[] { AgentClient.AGENT_CLIENT.CLIENT_ID }, Keys.CLIENT_PKEY, new TableField[] { Client.CLIENT.ID }, true);
    public static final ForeignKey<ClientModelRecord, ClientRecord> CLIENT_MODEL__FK_CLIENT_MODEL_CLIENT = Internal.createForeignKey(ClientModel.CLIENT_MODEL, DSL.name("fk_client_model_client"), new TableField[] { ClientModel.CLIENT_MODEL.CLIENT_ID }, Keys.CLIENT_PKEY, new TableField[] { Client.CLIENT.ID }, true);
    public static final ForeignKey<ClientModelRecord, ModelRecord> CLIENT_MODEL__FK_CLIENT_MODEL_MODEL = Internal.createForeignKey(ClientModel.CLIENT_MODEL, DSL.name("fk_client_model_model"), new TableField[] { ClientModel.CLIENT_MODEL.MODEL_ID }, Keys.MODEL_PKEY, new TableField[] { Model.MODEL.ID }, true);
    public static final ForeignKey<ClientRagRecord, ClientRecord> CLIENT_RAG__FK_CLIENT_RAG_CLIENT = Internal.createForeignKey(ClientRag.CLIENT_RAG, DSL.name("fk_client_rag_client"), new TableField[] { ClientRag.CLIENT_RAG.CLIENT_ID }, Keys.CLIENT_PKEY, new TableField[] { Client.CLIENT.ID }, true);
    public static final ForeignKey<ClientRagRecord, RagRecord> CLIENT_RAG__FK_CLIENT_RAG_RAG = Internal.createForeignKey(ClientRag.CLIENT_RAG, DSL.name("fk_client_rag_rag"), new TableField[] { ClientRag.CLIENT_RAG.RAG_ID }, Keys.RAG_PKEY, new TableField[] { Rag.RAG.ID }, true);
}
