/*
 * This file is generated by jOOQ.
 */
package com.example.jooq;


import com.example.jooq.tables.Agent;
import com.example.jooq.tables.AgentMcp;
import com.example.jooq.tables.AgentMemory;
import com.example.jooq.tables.AgentModel;
import com.example.jooq.tables.AgentRag;
import com.example.jooq.tables.KgEntity;
import com.example.jooq.tables.Mcp;
import com.example.jooq.tables.Model;
import com.example.jooq.tables.Orchestrator;
import com.example.jooq.tables.OrchestratorAgent;
import com.example.jooq.tables.OrchestratorMessage;
import com.example.jooq.tables.OrchestratorRun;
import com.example.jooq.tables.Rag;
import com.example.jooq.tables.VectorDocument;
import com.example.jooq.tables.records.AgentMcpRecord;
import com.example.jooq.tables.records.AgentMemoryRecord;
import com.example.jooq.tables.records.AgentModelRecord;
import com.example.jooq.tables.records.AgentRagRecord;
import com.example.jooq.tables.records.AgentRecord;
import com.example.jooq.tables.records.KgEntityRecord;
import com.example.jooq.tables.records.McpRecord;
import com.example.jooq.tables.records.ModelRecord;
import com.example.jooq.tables.records.OrchestratorAgentRecord;
import com.example.jooq.tables.records.OrchestratorMessageRecord;
import com.example.jooq.tables.records.OrchestratorRecord;
import com.example.jooq.tables.records.OrchestratorRunRecord;
import com.example.jooq.tables.records.RagRecord;
import com.example.jooq.tables.records.VectorDocumentRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AgentRecord> AGENT_PKEY = Internal.createUniqueKey(Agent.AGENT, DSL.name("agent_pkey"), new TableField[] { Agent.AGENT.ID }, true);
    public static final UniqueKey<AgentMcpRecord> PK_AGENT_MCP = Internal.createUniqueKey(AgentMcp.AGENT_MCP, DSL.name("pk_agent_mcp"), new TableField[] { AgentMcp.AGENT_MCP.AGENT_ID, AgentMcp.AGENT_MCP.MCP_ID }, true);
    public static final UniqueKey<AgentMemoryRecord> AGENT_MEMORY_PKEY = Internal.createUniqueKey(AgentMemory.AGENT_MEMORY, DSL.name("agent_memory_pkey"), new TableField[] { AgentMemory.AGENT_MEMORY.ID }, true);
    public static final UniqueKey<AgentModelRecord> PK_AGENT_MODEL = Internal.createUniqueKey(AgentModel.AGENT_MODEL, DSL.name("pk_agent_model"), new TableField[] { AgentModel.AGENT_MODEL.AGENT_ID, AgentModel.AGENT_MODEL.MODEL_ID }, true);
    public static final UniqueKey<AgentRagRecord> PK_AGENT_RAG = Internal.createUniqueKey(AgentRag.AGENT_RAG, DSL.name("pk_agent_rag"), new TableField[] { AgentRag.AGENT_RAG.AGENT_ID, AgentRag.AGENT_RAG.RAG_ID }, true);
    public static final UniqueKey<KgEntityRecord> KG_ENTITY_PKEY = Internal.createUniqueKey(KgEntity.KG_ENTITY, DSL.name("kg_entity_pkey"), new TableField[] { KgEntity.KG_ENTITY.ID }, true);
    public static final UniqueKey<McpRecord> MCP_PKEY = Internal.createUniqueKey(Mcp.MCP, DSL.name("mcp_pkey"), new TableField[] { Mcp.MCP.ID }, true);
    public static final UniqueKey<ModelRecord> MODEL_PKEY = Internal.createUniqueKey(Model.MODEL, DSL.name("model_pkey"), new TableField[] { Model.MODEL.ID }, true);
    public static final UniqueKey<OrchestratorRecord> ORCHESTRATOR_PKEY = Internal.createUniqueKey(Orchestrator.ORCHESTRATOR, DSL.name("orchestrator_pkey"), new TableField[] { Orchestrator.ORCHESTRATOR.ID }, true);
    public static final UniqueKey<OrchestratorAgentRecord> PK_ORCHESTRATOR_AGENT = Internal.createUniqueKey(OrchestratorAgent.ORCHESTRATOR_AGENT, DSL.name("pk_orchestrator_agent"), new TableField[] { OrchestratorAgent.ORCHESTRATOR_AGENT.ORCHESTRATOR_ID, OrchestratorAgent.ORCHESTRATOR_AGENT.AGENT_ID }, true);
    public static final UniqueKey<OrchestratorMessageRecord> ORCHESTRATOR_MESSAGE_PKEY = Internal.createUniqueKey(OrchestratorMessage.ORCHESTRATOR_MESSAGE, DSL.name("orchestrator_message_pkey"), new TableField[] { OrchestratorMessage.ORCHESTRATOR_MESSAGE.ID }, true);
    public static final UniqueKey<OrchestratorRunRecord> ORCHESTRATOR_RUN_PKEY = Internal.createUniqueKey(OrchestratorRun.ORCHESTRATOR_RUN, DSL.name("orchestrator_run_pkey"), new TableField[] { OrchestratorRun.ORCHESTRATOR_RUN.ID }, true);
    public static final UniqueKey<RagRecord> RAG_PKEY = Internal.createUniqueKey(Rag.RAG, DSL.name("rag_pkey"), new TableField[] { Rag.RAG.ID }, true);
    public static final UniqueKey<VectorDocumentRecord> VECTOR_DOCUMENT_PKEY = Internal.createUniqueKey(VectorDocument.VECTOR_DOCUMENT, DSL.name("vector_document_pkey"), new TableField[] { VectorDocument.VECTOR_DOCUMENT.EMBEDDING_ID }, true);
}
