/*
 * This file is generated by jOOQ.
 */
package com.example.jooq;


import com.example.jooq.tables.Agent;
import com.example.jooq.tables.AgentClient;
import com.example.jooq.tables.Client;
import com.example.jooq.tables.ClientMcp;
import com.example.jooq.tables.ClientModel;
import com.example.jooq.tables.ClientRag;
import com.example.jooq.tables.Mcp;
import com.example.jooq.tables.Model;
import com.example.jooq.tables.Rag;
import com.example.jooq.tables.VectorDocument;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * Agent表
     */
    public final Agent AGENT = Agent.AGENT;

    /**
     * Agent和Client的关联表
     */
    public final AgentClient AGENT_CLIENT = AgentClient.AGENT_CLIENT;

    /**
     * Client表
     */
    public final Client CLIENT = Client.CLIENT;

    /**
     * Client和MCP的关联表
     */
    public final ClientMcp CLIENT_MCP = ClientMcp.CLIENT_MCP;

    /**
     * Client和Model的关联表
     */
    public final ClientModel CLIENT_MODEL = ClientModel.CLIENT_MODEL;

    /**
     * Client和RAG的关联表
     */
    public final ClientRag CLIENT_RAG = ClientRag.CLIENT_RAG;

    /**
     * MCP表（Model Context Protocol）
     */
    public final Mcp MCP = Mcp.MCP;

    /**
     * Model表
     */
    public final Model MODEL = Model.MODEL;

    /**
     * RAG表（Retrieval-Augmented Generation）
     */
    public final Rag RAG = Rag.RAG;

    /**
     * The table <code>public.vector_document</code>.
     */
    public final VectorDocument VECTOR_DOCUMENT = VectorDocument.VECTOR_DOCUMENT;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Agent.AGENT,
            AgentClient.AGENT_CLIENT,
            Client.CLIENT,
            ClientMcp.CLIENT_MCP,
            ClientModel.CLIENT_MODEL,
            ClientRag.CLIENT_RAG,
            Mcp.MCP,
            Model.MODEL,
            Rag.RAG,
            VectorDocument.VECTOR_DOCUMENT
        );
    }
}
