/*
 * This file is generated by jOOQ.
 */
package com.example.jooq;


import com.example.jooq.tables.Agent;
import com.example.jooq.tables.AgentMcp;
import com.example.jooq.tables.AgentMemory;
import com.example.jooq.tables.AgentModel;
import com.example.jooq.tables.AgentRag;
import com.example.jooq.tables.Doc;
import com.example.jooq.tables.KgEntity;
import com.example.jooq.tables.Mcp;
import com.example.jooq.tables.Model;
import com.example.jooq.tables.Orchestrator;
import com.example.jooq.tables.OrchestratorAgent;
import com.example.jooq.tables.OrchestratorMessage;
import com.example.jooq.tables.OrchestratorRun;
import com.example.jooq.tables.Rag;
import com.example.jooq.tables.VectorDocument;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.agent</code>.
     */
    public final Agent AGENT = Agent.AGENT;

    /**
     * The table <code>public.agent_mcp</code>.
     */
    public final AgentMcp AGENT_MCP = AgentMcp.AGENT_MCP;

    /**
     * The table <code>public.agent_memory</code>.
     */
    public final AgentMemory AGENT_MEMORY = AgentMemory.AGENT_MEMORY;

    /**
     * The table <code>public.agent_model</code>.
     */
    public final AgentModel AGENT_MODEL = AgentModel.AGENT_MODEL;

    /**
     * The table <code>public.agent_rag</code>.
     */
    public final AgentRag AGENT_RAG = AgentRag.AGENT_RAG;

    /**
     * The table <code>public.doc</code>.
     */
    public final Doc DOC = Doc.DOC;

    /**
     * The table <code>public.kg_entity</code>.
     */
    public final KgEntity KG_ENTITY = KgEntity.KG_ENTITY;

    /**
     * The table <code>public.mcp</code>.
     */
    public final Mcp MCP = Mcp.MCP;

    /**
     * The table <code>public.model</code>.
     */
    public final Model MODEL = Model.MODEL;

    /**
     * The table <code>public.orchestrator</code>.
     */
    public final Orchestrator ORCHESTRATOR = Orchestrator.ORCHESTRATOR;

    /**
     * The table <code>public.orchestrator_agent</code>.
     */
    public final OrchestratorAgent ORCHESTRATOR_AGENT = OrchestratorAgent.ORCHESTRATOR_AGENT;

    /**
     * The table <code>public.orchestrator_message</code>.
     */
    public final OrchestratorMessage ORCHESTRATOR_MESSAGE = OrchestratorMessage.ORCHESTRATOR_MESSAGE;

    /**
     * The table <code>public.orchestrator_run</code>.
     */
    public final OrchestratorRun ORCHESTRATOR_RUN = OrchestratorRun.ORCHESTRATOR_RUN;

    /**
     * The table <code>public.rag</code>.
     */
    public final Rag RAG = Rag.RAG;

    /**
     * The table <code>public.vector_document</code>.
     */
    public final VectorDocument VECTOR_DOCUMENT = VectorDocument.VECTOR_DOCUMENT;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Agent.AGENT,
            AgentMcp.AGENT_MCP,
            AgentMemory.AGENT_MEMORY,
            AgentModel.AGENT_MODEL,
            AgentRag.AGENT_RAG,
            Doc.DOC,
            KgEntity.KG_ENTITY,
            Mcp.MCP,
            Model.MODEL,
            Orchestrator.ORCHESTRATOR,
            OrchestratorAgent.ORCHESTRATOR_AGENT,
            OrchestratorMessage.ORCHESTRATOR_MESSAGE,
            OrchestratorRun.ORCHESTRATOR_RUN,
            Rag.RAG,
            VectorDocument.VECTOR_DOCUMENT
        );
    }
}
