/*
 * This file is generated by jOOQ.
 */
package com.example.jooq;


import com.example.jooq.tables.Agent;
import com.example.jooq.tables.AgentMcp;
import com.example.jooq.tables.AgentMemory;
import com.example.jooq.tables.AgentModel;
import com.example.jooq.tables.AgentRag;
import com.example.jooq.tables.Mcp;
import com.example.jooq.tables.Model;
import com.example.jooq.tables.Orchestrator;
import com.example.jooq.tables.OrchestratorAgent;
import com.example.jooq.tables.OrchestratorMessage;
import com.example.jooq.tables.OrchestratorRun;
import com.example.jooq.tables.Rag;
import com.example.jooq.tables.VectorDocument;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * Agent表（智能体）
     */
    public final Agent AGENT = Agent.AGENT;

    /**
     * Agent与MCP的关联表
     */
    public final AgentMcp AGENT_MCP = AgentMcp.AGENT_MCP;

    /**
     * Agent共享记忆表，支持会话级和全局级别的记忆存储
     */
    public final AgentMemory AGENT_MEMORY = AgentMemory.AGENT_MEMORY;

    /**
     * Agent与Model的关联表
     */
    public final AgentModel AGENT_MODEL = AgentModel.AGENT_MODEL;

    /**
     * Agent与RAG的关联表
     */
    public final AgentRag AGENT_RAG = AgentRag.AGENT_RAG;

    /**
     * MCP表（Model Context Protocol）
     */
    public final Mcp MCP = Mcp.MCP;

    /**
     * Model表
     */
    public final Model MODEL = Model.MODEL;

    /**
     * Orchestrator表（编排器）
     */
    public final Orchestrator ORCHESTRATOR = Orchestrator.ORCHESTRATOR;

    /**
     * Orchestrator与Agent的关联表
     */
    public final OrchestratorAgent ORCHESTRATOR_AGENT = OrchestratorAgent.ORCHESTRATOR_AGENT;

    /**
     * Orchestrator消息记录表，记录所有Agent间的交互信息
     */
    public final OrchestratorMessage ORCHESTRATOR_MESSAGE = OrchestratorMessage.ORCHESTRATOR_MESSAGE;

    /**
     * Orchestrator执行会话表，记录每次Orchestrator执行的完整信息
     */
    public final OrchestratorRun ORCHESTRATOR_RUN = OrchestratorRun.ORCHESTRATOR_RUN;

    /**
     * RAG表（Retrieval-Augmented Generation）
     */
    public final Rag RAG = Rag.RAG;

    /**
     * 存储向量嵌入数据的表
     */
    public final VectorDocument VECTOR_DOCUMENT = VectorDocument.VECTOR_DOCUMENT;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Agent.AGENT,
            AgentMcp.AGENT_MCP,
            AgentMemory.AGENT_MEMORY,
            AgentModel.AGENT_MODEL,
            AgentRag.AGENT_RAG,
            Mcp.MCP,
            Model.MODEL,
            Orchestrator.ORCHESTRATOR,
            OrchestratorAgent.ORCHESTRATOR_AGENT,
            OrchestratorMessage.ORCHESTRATOR_MESSAGE,
            OrchestratorRun.ORCHESTRATOR_RUN,
            Rag.RAG,
            VectorDocument.VECTOR_DOCUMENT
        );
    }
}
