/*
 * This file is generated by jOOQ.
 */
package com.example.jooq;


import com.example.jooq.tables.Agent;
import com.example.jooq.tables.AgentMcp;
import com.example.jooq.tables.AgentMemory;
import com.example.jooq.tables.AgentModel;
import com.example.jooq.tables.AgentRag;
import com.example.jooq.tables.Doc;
import com.example.jooq.tables.KgEntity;
import com.example.jooq.tables.Mcp;
import com.example.jooq.tables.Model;
import com.example.jooq.tables.Orchestrator;
import com.example.jooq.tables.OrchestratorAgent;
import com.example.jooq.tables.OrchestratorMessage;
import com.example.jooq.tables.OrchestratorRun;
import com.example.jooq.tables.Rag;
import com.example.jooq.tables.VectorDocument;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>public.agent</code>.
     */
    public static final Agent AGENT = Agent.AGENT;

    /**
     * The table <code>public.agent_mcp</code>.
     */
    public static final AgentMcp AGENT_MCP = AgentMcp.AGENT_MCP;

    /**
     * The table <code>public.agent_memory</code>.
     */
    public static final AgentMemory AGENT_MEMORY = AgentMemory.AGENT_MEMORY;

    /**
     * The table <code>public.agent_model</code>.
     */
    public static final AgentModel AGENT_MODEL = AgentModel.AGENT_MODEL;

    /**
     * The table <code>public.agent_rag</code>.
     */
    public static final AgentRag AGENT_RAG = AgentRag.AGENT_RAG;

    /**
     * The table <code>public.doc</code>.
     */
    public static final Doc DOC = Doc.DOC;

    /**
     * The table <code>public.kg_entity</code>.
     */
    public static final KgEntity KG_ENTITY = KgEntity.KG_ENTITY;

    /**
     * The table <code>public.mcp</code>.
     */
    public static final Mcp MCP = Mcp.MCP;

    /**
     * The table <code>public.model</code>.
     */
    public static final Model MODEL = Model.MODEL;

    /**
     * The table <code>public.orchestrator</code>.
     */
    public static final Orchestrator ORCHESTRATOR = Orchestrator.ORCHESTRATOR;

    /**
     * The table <code>public.orchestrator_agent</code>.
     */
    public static final OrchestratorAgent ORCHESTRATOR_AGENT = OrchestratorAgent.ORCHESTRATOR_AGENT;

    /**
     * The table <code>public.orchestrator_message</code>.
     */
    public static final OrchestratorMessage ORCHESTRATOR_MESSAGE = OrchestratorMessage.ORCHESTRATOR_MESSAGE;

    /**
     * The table <code>public.orchestrator_run</code>.
     */
    public static final OrchestratorRun ORCHESTRATOR_RUN = OrchestratorRun.ORCHESTRATOR_RUN;

    /**
     * The table <code>public.rag</code>.
     */
    public static final Rag RAG = Rag.RAG;

    /**
     * The table <code>public.vector_document</code>.
     */
    public static final VectorDocument VECTOR_DOCUMENT = VectorDocument.VECTOR_DOCUMENT;
}
