/*
 * This file is generated by jOOQ.
 */
package com.example.jooq;


import com.example.jooq.tables.Agent;
import com.example.jooq.tables.AgentMcp;
import com.example.jooq.tables.AgentMemory;
import com.example.jooq.tables.AgentModel;
import com.example.jooq.tables.AgentRag;
import com.example.jooq.tables.Mcp;
import com.example.jooq.tables.Model;
import com.example.jooq.tables.Orchestrator;
import com.example.jooq.tables.OrchestratorAgent;
import com.example.jooq.tables.OrchestratorMessage;
import com.example.jooq.tables.OrchestratorRun;
import com.example.jooq.tables.Rag;
import com.example.jooq.tables.VectorDocument;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * Agent表（智能体）
     */
    public static final Agent AGENT = Agent.AGENT;

    /**
     * Agent与MCP的关联表
     */
    public static final AgentMcp AGENT_MCP = AgentMcp.AGENT_MCP;

    /**
     * Agent共享记忆表，支持会话级和全局级别的记忆存储
     */
    public static final AgentMemory AGENT_MEMORY = AgentMemory.AGENT_MEMORY;

    /**
     * Agent与Model的关联表
     */
    public static final AgentModel AGENT_MODEL = AgentModel.AGENT_MODEL;

    /**
     * Agent与RAG的关联表
     */
    public static final AgentRag AGENT_RAG = AgentRag.AGENT_RAG;

    /**
     * MCP表（Model Context Protocol）
     */
    public static final Mcp MCP = Mcp.MCP;

    /**
     * Model表
     */
    public static final Model MODEL = Model.MODEL;

    /**
     * Orchestrator表（编排器）
     */
    public static final Orchestrator ORCHESTRATOR = Orchestrator.ORCHESTRATOR;

    /**
     * Orchestrator与Agent的关联表
     */
    public static final OrchestratorAgent ORCHESTRATOR_AGENT = OrchestratorAgent.ORCHESTRATOR_AGENT;

    /**
     * Orchestrator消息记录表，记录所有Agent间的交互信息
     */
    public static final OrchestratorMessage ORCHESTRATOR_MESSAGE = OrchestratorMessage.ORCHESTRATOR_MESSAGE;

    /**
     * Orchestrator执行会话表，记录每次Orchestrator执行的完整信息
     */
    public static final OrchestratorRun ORCHESTRATOR_RUN = OrchestratorRun.ORCHESTRATOR_RUN;

    /**
     * RAG表（Retrieval-Augmented Generation）
     */
    public static final Rag RAG = Rag.RAG;

    /**
     * 存储向量嵌入数据的表
     */
    public static final VectorDocument VECTOR_DOCUMENT = VectorDocument.VECTOR_DOCUMENT;
}
