/*
 * This file is generated by jOOQ.
 */
package com.example.jooq;


import com.example.jooq.tables.Agent;
import com.example.jooq.tables.AgentClient;
import com.example.jooq.tables.Client;
import com.example.jooq.tables.ClientMcp;
import com.example.jooq.tables.ClientModel;
import com.example.jooq.tables.ClientRag;
import com.example.jooq.tables.Mcp;
import com.example.jooq.tables.Model;
import com.example.jooq.tables.Rag;
import com.example.jooq.tables.VectorDocument;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * Agent表
     */
    public static final Agent AGENT = Agent.AGENT;

    /**
     * Agent和Client的关联表
     */
    public static final AgentClient AGENT_CLIENT = AgentClient.AGENT_CLIENT;

    /**
     * Client表
     */
    public static final Client CLIENT = Client.CLIENT;

    /**
     * Client和MCP的关联表
     */
    public static final ClientMcp CLIENT_MCP = ClientMcp.CLIENT_MCP;

    /**
     * Client和Model的关联表
     */
    public static final ClientModel CLIENT_MODEL = ClientModel.CLIENT_MODEL;

    /**
     * Client和RAG的关联表
     */
    public static final ClientRag CLIENT_RAG = ClientRag.CLIENT_RAG;

    /**
     * MCP表（Model Context Protocol）
     */
    public static final Mcp MCP = Mcp.MCP;

    /**
     * Model表
     */
    public static final Model MODEL = Model.MODEL;

    /**
     * RAG表（Retrieval-Augmented Generation）
     */
    public static final Rag RAG = Rag.RAG;

    /**
     * The table <code>public.vector_document</code>.
     */
    public static final VectorDocument VECTOR_DOCUMENT = VectorDocument.VECTOR_DOCUMENT;
}
